### ISSUE TITLE
Enable yasd cause some problem

### ISSUE THREAD

**Issue by ray-wish** [swoole/yasd#10]
I enable yasd extension.
I use php-cs-fixer in vscode then it will enter the debug mode like enter php -e test.php.
I think it is a bug.
Could you fix it! 

Thank you very much^^

PS. I use phpbrew and ubuntu 18.04.
![image](https://user-images.githubusercontent.com/74281171/101146228-b6af6480-3655-11eb-897d-c659afc8543e.png)
![image](https://user-images.githubusercontent.com/74281171/101146357-db0b4100-3655-11eb-9c04-326306ed0e9a.png)

**Comment by huanghantao** [comment]
It looks like php-cs-fixer will turn on `-e`. Maybe we shouldn't use `-e` to decide whether to turn on the extension or not. Maybe we should add a configuration such as `yasd.enable =yes`. I will modify it.

**Comment by huanghantao** [comment]
> It looks like phpbrew will turn on `-e`. Maybe we shouldn't use `-e` to decide whether to turn on the extension or not. Maybe we should add a configuration such as `yasd.enable =yes`? However, I think it has the same effect as closing extensions.

**Comment by huanghantao** [comment]
It looks like phpbrew will turn on -e. Maybe we shouldn't use -e to decide whether to turn on the extension or not. Maybe we should add a configuration such as yasd.enable =yes? However, I think it has the same effect as closing extensions.

**Comment by huanghantao** [comment]
Have you installed any other debuggers? For example, xdebug?

**Comment by ray-wish** [comment]
Yes, I install xdebug!

**Comment by ray-wish** [comment]
@huanghantao I disable xdebug then yasd looks like resume normally.

**Comment by huanghantao** [comment]
@ray-wish Yes, yasd and xdebug can not installed at the same time, because xdebug will automatically set `- e`
