### ISSUE TITLE
malloc: can't allocate region

### ISSUE THREAD

**Issue by niezuxue** [swoole/yasd#109]
hyperf用view组件，controller中
`return $render->render('doc.index');`
index.blade.php文件中有引用css和js文件

我打的断点在 
![image](https://user-images.githubusercontent.com/8871650/113103029-5c07cd00-9231-11eb-84dc-8d4246640e7f.png)
当第二次走到这个断点时，debug信息就看不到了
![image](https://user-images.githubusercontent.com/8871650/113103425-d89aab80-9231-11eb-8fd7-646cd5b3bb12.png)

相应的控制台
php(74495,0x1188b75c0) malloc: can't allocate region
*** mach_vm_map(size=8030604640798470144) failed (error code=3)
php(74495,0x1188b75c0) malloc: *** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
[2021-03-31 14:52:52 $74482.0]  WARNING check_worker_exit_status: worker#0[pid=74495] abnormal exit, status=0, signal=6

我机器目前的内存应该是够的
![image](https://user-images.githubusercontent.com/8871650/113103368-c7ea3580-9231-11eb-98df-2acb388e8c39.png)

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
