### ISSUE TITLE
vscode breakpoint doesn't work under wsl2

### ISSUE THREAD

**Issue by noyidoit** [swoole/yasd#110]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provides a simple script and debug step to reproduce the problem.

After setting breakpoint and starting debugging (F5) under VS Code, I enter `php -e test.php` under wsl2, and nothing happened.

2. What did you expect to see?
The breakpoint should normally work, just like this video - [在IDE中使用yasd调试器](https://course.swoole-cloud.com/course-video/136).

3. What did you see instead?
Breakpoint doesn't work on vscode.
![image](https://user-images.githubusercontent.com/26378591/114077541-836a3400-98da-11eb-8f2f-2a892f9b76c2.png)

4. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
Linux xxxxxxx 5.4.72-microsoft-standard-WSL2 #1 SMP xxxxxxxx x86_64 x86_64 x86_64 GNU/Linux
```

```
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Yasd v0.3.7, Our Copyright, by codinghuang
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
```

And here's my `launch.json`
![image](https://user-images.githubusercontent.com/26378591/114078064-11deb580-98db-11eb-8cf9-fd76a3a61408.png)

(cli) `php.ini`
![image](https://user-images.githubusercontent.com/26378591/114078166-30dd4780-98db-11eb-9f84-b54a9bd52819.png)

`php --ri yasd`
![image](https://user-images.githubusercontent.com/26378591/114078242-47839e80-98db-11eb-8080-d8c7b40ce95a.png)

**Comment by huanghantao** [comment]
Perhaps you need to modify `remote_host`, you should not be able to access Windows in WSL.

**Comment by noyidoit** [comment]
> Perhaps you need to modify `remote_host`, you should not be able to access Windows by `127.0.0.1` in WSL.

Thanks for you reply, 

After following your advice, I have googled and tried 2 ways to find ip address could access Windows from WSL2, all comes out the same ip address ( and I guess that's it? )
```bash
# bash
grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'

ipconfig.exe | grep 'vEthernet (WSL)' -A4 | cut -d":" -f 2 | tail -n1 | sed -e 's/\s*//g'
```
![image](https://user-images.githubusercontent.com/26378591/114120965-209b8b80-9920-11eb-88bd-2829f3e7efb9.png)

In additional, I have turn off windows defender firewall
```cmd
# cmd
New-NetFirewallRule -DisplayName "WSL" -Direction Inbound  -InterfaceAlias "vEthernet (WSL)"  -Action Allow
```
And modified php.ini yasd.remote.host ( also I have tried another port , of course I have modified launch.json too)

![image](https://user-images.githubusercontent.com/26378591/114121026-3741e280-9920-11eb-8922-40c989741006.png)

Unfortunately, just as the same,  it seems not work. XD

**Comment by noyidoit** [comment]
WTF, I found my php.ini have a TYPO
ysad -> yasd

**Comment by noyidoit** [comment]
Thanks, it could successfully debug now !!

And `127.0.0.1` is working, just for me.

Here's my configure if anyone needed:

VS Code launch.json
![image](https://user-images.githubusercontent.com/26378591/114123358-b89b7400-9924-11eb-8913-80672cc366ba.png)

php.ini
![image](https://user-images.githubusercontent.com/26378591/114123404-d072f800-9924-11eb-8ac2-c809bdc62ad4.png)
