### ISSUE TITLE
phptorm2020|2021版本里监听不到端口，phpstorm2019没问题

### ISSUE THREAD

**Issue by wangsen2020** [swoole/yasd#112]
采用virtualBo安装centos7.8操作系统，然后按照文档装机phpstorm2020监听不到，之前安装sdebug2.6时，也有这个问题，但是后来sdebug2.7解决了phpstorm2020监听不到的问题，还请yasd团队，参照sdebug2.7改进点，来兼容下phpstorm2020

备注:据说使用wsl的用户没有这个问题

**Comment by huanghantao** [comment]
现排查为什么你在虚拟机里面无法连接`yasd.remote_host`和`yasd.remote_port`指定的端口.

**Comment by wangsen2020** [comment]
我在虚拟机里面可以telnet 9000端口，phpstorm2020也可以接收来自虚拟机的tcp链接，并且建立了链接

这些都没有问题，问题就是，访问hyperf时，在IndexController-&gt;index函数打断点，断点不到，这个问题只发生在phpstorm2020+版本，phpstorm2019版本完全没问题，请别再讨论我的配置问题了，配置都没有问题的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午3:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [swoole/yasd] phptorm2020|2021版本里监听不到端口，phpstorm2019没问题 (#112)





 
先排查为什么你在虚拟机里面无法连接yasd.remote_host和yasd.remote_port指定的端口.

**Comment by wangsen2020** [comment]
我绝不是无理取闹，yasd的xdebug是不是用的要比sdebug2.7要低，之前sdebug2.6时，phpstorm2020就是监听不到的，还请大神们留意一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "swoole/yasd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月21日(星期三) 下午3:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [swoole/yasd] phptorm2020|2021版本里监听不到端口，phpstorm2019没问题 (#112)





 
先排查为什么你在虚拟机里面无法连接yasd.remote_host和yasd.remote_port指定的端口.

**Comment by huanghantao** [comment]
本来不想管了，和你解释一下为什么我直接关闭issue。第一，这个issue基本上没有说明任何环境，第二，没有操作步骤和相应的截图，第三，在你缺少必要信息的情况下，开发人员有必要询问你一些基本的信息，最后，你的态度影响了我的心情。

**Comment by huanghantao** [comment]
加我微信：codinghuang，微信上方便沟通。
