### ISSUE TITLE
希望有更多更详细的教程

### ISSUE THREAD

**Issue by huangdijia** [swoole/yasd#116]
文档里教程比较少，希望有更多更详细的教程，比如怎么调试 Swoole/Hyperf/Swoft 框架里的 HTTP 请求，和更多场景的调试教程。

另外弱弱的问一下，什么时候能支持 pecl 安装/升级。

**Comment by huanghantao** [comment]
Swoole有部分教程：https://course.swoole-cloud.com/videos

如果有哪些不会的地方，可以加我微信codinghuang

**Comment by huangdijia** [comment]
> Swoole微课程有部分视频教程：https://course.swoole-cloud.com/videos
> 
> 如果有哪些不会的地方，可以加我微信codinghuang

谢谢！已经在视频里找到答案。
