### ISSUE TITLE
是否支持 Mac M1

### ISSUE THREAD

**Issue by hualsy** [swoole/yasd#117]
我安装完后,
php -v 的报错如下 :
PHP Warning:  Failed loading Zend extension 'yasd' (tried: /usr/local/lib/php/pecl/20190902/yasd (dlopen(/usr/local/lib/php/pecl/20190902/yasd, 9): image not found), /usr/local/lib/php/pecl/20190902/yasd.so (dlopen(/usr/local/lib/php/pecl/20190902/yasd.so, 9): no suitable image found.  Did find:
	/usr/local/lib/php/pecl/20190902/yasd.so: mach-o, but wrong architecture
	/usr/local/lib/php/pecl/20190902/yasd.so: mach-o, but wrong architecture)) in Unknown on line 0

Warning: Failed loading Zend extension 'yasd' (tried: /usr/local/lib/php/pecl/20190902/yasd (dlopen(/usr/local/lib/php/pecl/20190902/yasd, 9): image not found), /usr/local/lib/php/pecl/20190902/yasd.so (dlopen(/usr/local/lib/php/pecl/20190902/yasd.so, 9): no suitable image found.  Did find:
	/usr/local/lib/php/pecl/20190902/yasd.so: mach-o, but wrong architecture
	/usr/local/lib/php/pecl/20190902/yasd.so: mach-o, but wrong architecture)) in Unknown on line 0
PHP 7.4.13 (cli) (built: Nov 30 2020 14:57:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies

其他扩展都可以安装使用，如swoole，redis等
系统版本为 macOS Big Sur

**Comment by huanghantao** [comment]
暂时没试过，后面会支持

**Comment by izhangxm** [comment]
@huanghantao 2022年了 还支持吗 m1的mac yasd还是无法编译成功的

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1

**Comment by shionphan** [comment]
目前无解，已在x86上编译号，然后再放到M1相应的目录下，即可正常运转。
