### ISSUE TITLE
Swoole http server stops on restart of Docker when yasd is turned  on

### ISSUE THREAD

**Issue by babarinde** [swoole/yasd#126]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provides a simple script and debug step to reproduce the problem.
I use VS code and Swoole Docker - php8 dev and running Mezzio on Linux
Everything was working really fine, even with supervisor and inotify but recently i noticed when i turn on yasd and i restart the container so the yasd can work, i see this
[logs](https://gist.github.com/babarinde/51adf6231eb1ccc4f863931fbbc9a094)

When i stop yasd i see this message
`[yasd] recv command error, connection closed`

but when i stop yasd, Swoole works fine

2. What did you expect to see?
SWoole http server working with yasd and stopping at break points

3. What did you see instead?
[logs](https://gist.github.com/babarinde/51adf6231eb1ccc4f863931fbbc9a094)

4. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
On Docker:
`uname -a:
Linux f271c7329e8c 5.8.18-100.fc31.x86_64 #1 SMP Mon Nov 2 20:32:55 UTC 2020 x86_64 GNU/Linux`

`php -v
PHP 8.0.3 (cli) (built: Apr 10 2021 13:10:41) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Yasd v0.3.7, Our Copyright, by codinghuang
`

`gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)`

[yasd is built like this in docker file](https://gist.github.com/babarinde/10501a58e4ecbe7e0a6a386678c47043)

**Comment by huanghantao** [comment]
You can open `yasd.log_level=0`, then start your debugging, and show me the `debug.log` file generated in the current directory.

**Comment by babarinde** [comment]
Thanks for your response.
[pls see debug.log output here](https://gist.github.com/babarinde/84c4d30e5dd81843c593399a86fa24f1)

**Comment by juslintek** [comment]
@babarinde but that always happens if you have a breakpoint in your app and the container uses `php -e some_script.php` as a command to keep the container running. :-)

For me biggest problem is that I yasd is not breaking on swoole server requests and cronjobs other executions, but breaking on file executions without swoole server...

**Comment by babarinde** [comment]
@juslintek this happens without any breakpoints, the moment i start running yasd and do a restart on docker-compose the swoole http server does not run, but the moment i stop yasd, the swoole server is started.
When yasd is not started before swoole http server is up i see this `[yasd] Connection refused`

**Comment by huanghantao** [comment]
> Thanks for your response.
> [pls see debug.log output here](https://gist.github.com/babarinde/84c4d30e5dd81843c593399a86fa24f1)
`yasd` currently does not support the `feature_get` command in the latest version of VScode. You can use the lower version of VScode instead.

**Comment by huanghantao** [comment]
@babarinde yasd currently support the the latest version of VScode at master branch.

**Comment by babarinde** [comment]
Are you asking me to update to latest VSCode then?

**Comment by huanghantao** [comment]
No, you can use your current VS code for debugging.

**Comment by babarinde** [comment]
Ok, So what do you think this issue relates to then?

**Comment by huanghantao** [comment]
From the `debug.log` you give, YASD did not previously support `feature_get`: 

```bash
feature_get -i 1 -n resolved_breakpoints
```

I just supported it #128

**Comment by babarinde** [comment]
That was fast and thanks for the promptness
Built yasd from v0.3.8 from my end its no longer blocking swoole http server, however its not stopping at the break point
