### ISSUE TITLE
启动项目报No route to host，编辑器也没有连接提示

### ISSUE THREAD

**Issue by Seele9** [swoole/yasd#127]
![image](https://user-images.githubusercontent.com/46363764/118245383-4eea2900-b4d3-11eb-9a0b-a0bcb8ce9b86.png)
![image](https://user-images.githubusercontent.com/46363764/118245424-5c071800-b4d3-11eb-9d71-fe3da87ad84f.png)

**Comment by huanghantao** [comment]
你可以确认下是否可以连接上remote_host和remote_port

**Comment by Seele9** [comment]
![image](https://user-images.githubusercontent.com/46363764/118250065-a63ec800-b4d8-11eb-8393-f80cfb4942e5.png)
包括telnet也无法连接本地机器 ，请问一下这种应该怎么看呢

**Comment by Seele9** [comment]
![image](https://user-images.githubusercontent.com/46363764/118250286-e2722880-b4d8-11eb-9f8a-3bff4da700dc.png)

**Comment by Seele9** [comment]
![Uploading image.png…]()

**Comment by Seele9** [comment]
![image](https://user-images.githubusercontent.com/46363764/118250383-fc137000-b4d8-11eb-913f-4a64e2d2a858.png)

**Comment by Seele9** [comment]
刚才IP弄错了  现在是启动项目特别慢  然后会报
![image](https://user-images.githubusercontent.com/46363764/118250811-6b895f80-b4d9-11eb-9bf9-53e0911760fd.png)

**Comment by Seele9** [comment]
解决了谢谢
