### ISSUE TITLE
执行命令，一直报 program is not running!错误

### ISSUE THREAD

**Issue by wulianggit** [swoole/yasd#13]
扩展安装结果，如下：
![image](https://user-images.githubusercontent.com/19743805/101432483-e4d9c080-3943-11eb-9b02-650b796973c8.png)

执行：n、f、s 这些命令的时候就会报错
![image](https://user-images.githubusercontent.com/19743805/101432653-35511e00-3944-11eb-811f-c81ae9e4303b.png)

请问这是什么原因呢？

**Comment by huanghantao** [comment]
请先输入`r`命令，让处于运行状态

**Comment by wulianggit** [comment]
> 请先输入`r`命令，让处于运行状态

请问下普通的PHP脚本，不用Swoole可以调试吗

**Comment by huanghantao** [comment]
> > 请先输入`r`命令，让处于运行状态
> 
> 请问下普通的PHP脚本，不用Swoole可以调试吗

可以的

**Comment by wulianggit** [comment]
> > > 请先输入`r`命令，让处于运行状态
> > 
> > 
> > 请问下普通的PHP脚本，不用Swoole可以调试吗
> 
> 可以的

> 请问下，为什么每次删除断点后，重新启动还是有断点，显示如下：
![image](https://user-images.githubusercontent.com/19743805/101435359-30419e00-3947-11eb-89e7-a092e8f2fcee.png)

**Comment by huanghantao** [comment]
因为断点会被缓存在文件`.breakpoints_file.log`里面。
因为命令行没有IDE方便，无法记录之前的断点。如果你的断点在各种文件里面，你下次就要重新打一遍断点，非常的麻烦，所以这算是对命令行的一个优化。如果一不想要重新加载断点，把文件`.breakpoints_file.log`删了就好。

**Comment by huanghantao** [comment]
或者说，只删除文件里面的某一行即可，这样就会删除这个断点。

**Comment by wulianggit** [comment]
> 或者说，只删除文件里面的某一行即可，这样就会删除这个断点。

谢谢，明白了
