### ISSUE TITLE
提两个很重要的需求

### ISSUE THREAD

**Issue by liuquanhao** [swoole/yasd#131]
1.  remote_host能不能支持域名，用ip的话每次ip换了需要重新改配置，而且打包到docker里面每次还要更新dockerfile。
2. 能不能添加trigger_value，和xdebug3的一样，当有大量请求时，不希望什么请求都中断，只中断我自己设置了特殊参数的请求，这样才能调试。

**Comment by huanghantao** [comment]
用最新版本的yasd，这两个功能都是支持的。有疑问可以加我微信：codinghuang

**Comment by huanghantao** [comment]
解析域名的还在master分支，没打版本号，你可以用master分支的代码试试。

**Comment by liuquanhao** [comment]
> 解析域名的还在master分支，没打版本号，你可以用master分支的代码试试。

好的大佬，我现在试试，辛苦了，感谢

**Comment by im55cc** [comment]
trigger_value 值是怎么加的？文档里没看到呢。
