### ISSUE TITLE
How i can install this?

### ISSUE THREAD

**Issue by DilawskyJordan** [swoole/yasd#134]
Hello there, im sorry if i didn't understand installing steps but i found it difficult.

**Comment by huanghantao** [comment]
Simply copy these commands:

https://github.com/swoole/yasd#build

**Comment by DilawskyJordan** [comment]
This message shown from docker build 

make sure that you run '/usr/local/bin/phpize' in the top level source directory of the module

**Comment by huanghantao** [comment]
You should execute `phpize` in `yasd` directory.
