### ISSUE TITLE
hyperf 断点调试，打了断点，但是没有生效

### ISSUE THREAD

**Issue by wulianggit** [swoole/yasd#14]
> 1、如下是代码
![image](https://user-images.githubusercontent.com/19743805/101436702-a3e4aa80-3949-11eb-97c1-ee7dde03a602.png)

> 2、如下是操作过程；
首先使用了b命令在20行处打了断点；
然后使用了r命令;
> 3、问题：
代码跑起来，发现并没有输出 `stop at breakpoint` 
访问9501端口，代码报错

![image](https://user-images.githubusercontent.com/19743805/101437042-54eb4500-394a-11eb-80df-a0cc8bf8f437.png)

**Comment by huanghantao** [comment]
会不会是你代码错了，你看有`error`

**Comment by huanghantao** [comment]
你打断点可能有问题，断点显示是第`0`行，而不是`20`行

**Comment by huanghantao** [comment]
你要设置断点在文件的行数。

**Comment by huanghantao** [comment]
![24FB98A2-6A9E-4BF3-8E72-84B7D4C12A63](https://user-images.githubusercontent.com/22836925/101437066-5ddc1680-394a-11eb-80be-3c3e02b67ac9.png)

**Comment by wulianggit** [comment]
> 你要设置断点在文件的行数。

> 一样的，重新上传了图片

**Comment by huanghantao** [comment]
你不打断点能访问吗？

**Comment by wulianggit** [comment]
> 会不会是你代码错了，你看有`error`



> 你不打断点能访问吗？

可能是我代码有问题，我重新clone一份骨架代码试下。感觉跟断点没有关系

**Comment by sy-records** [comment]
on null这个问题执行`composer dumpautoload -o`，然后再跑下

**Comment by wulianggit** [comment]
> on null这个问题执行`composer dumpautoload -o`，然后再跑下

> 是的，执行之后不报错了，但还是无法断点

> 我在22行 `echo Hyperf`,控制台都有输出

![image](https://user-images.githubusercontent.com/19743805/101443374-3a1fcd00-3958-11eb-9183-d5d936868b3d.png)

**Comment by wulianggit** [comment]
> 你不打断点能访问吗？

执行了 `composer dump-autoload -o`，可以访问了，就是断点没效果

![image](https://user-images.githubusercontent.com/19743805/101443609-d053f300-3958-11eb-91ab-987d1b823c28.png)

**Comment by sy-records** [comment]
复现不了，你检查下你有没有其他扩展影响

![image](https://user-images.githubusercontent.com/33931153/101443950-70118100-3959-11eb-925b-4ebf60cba633.png)

**Comment by wulianggit** [comment]
> 复现不了，你检查下你有没有其他扩展影响
> 
> ![image](https://user-images.githubusercontent.com/33931153/101443950-70118100-3959-11eb-925b-4ebf60cba633.png)
> 总共就这么几个扩展，我再研究研究吧
![image](https://user-images.githubusercontent.com/19743805/101444391-5c1a4f00-395a-11eb-9507-357588f460b9.png)

**Comment by huanghantao** [comment]
你看看打断点的文件路径对不对？

**Comment by wulianggit** [comment]
> 你看看打断点的文件路径对不对？

文件路径没问题，绝对路径

**Comment by huanghantao** [comment]
并且，一个没有任何改动的`hyperf-skeleton`，第`20`行是无效行。

**Comment by huanghantao** [comment]
你把你的文件内容给我们看看。

**Comment by sy-records** [comment]
改成`zend_extension=yasd.so`

**Comment by huanghantao** [comment]
确实，是`zend_extension`的问题

**Comment by wulianggit** [comment]
> 改成`zend_extension=yasd.so`

这是正确解决方法
