### ISSUE TITLE
PHPstorm下单元测试如何进行debug

### ISSUE THREAD

**Issue by yimuczhou** [swoole/yasd#142]
我通过phpunit去进行调试代码，可以使用吗？我看介绍都是远程接口调用？

**Comment by huanghantao** [comment]
应该是可以的,为了和xdebug的行为保持一致,你可以配置:

```ini
yasd.open_extended_info=1
```

这样的话,相当于默认开启了`php -e`选项.

**Comment by YangHuiFor** [comment]
![image](https://user-images.githubusercontent.com/4995476/128346360-230962f9-8c2f-48df-98a3-7884284d7a70.png)
@huanghantao 不太行，
`Yasd => enabled
Author => codinghuang <codinghuang@qq.com>
Version => 0.3.9-alpha
Built => Aug  5 2021 17:00:00

Directive => Local Value => Master Value
yasd.breakpoints_file => no value => no value
yasd.debug_mode => remote => remote
yasd.remote_host => 127.0.0.1 => 127.0.0.1
yasd.remote_port => 9000 => 9000
yasd.depth => 1 => 1
yasd.log_level => -1 => -1
yasd.max_executed_opline_num => 0 => 0
yasd.init_file => no value => no value
yasd.open_extended_info => 1 => 1
xdebug.coverage_enable => 1 => 1
xdebug.profiler_enable => 1 => 1
xdebug.remote_autostart => 1 => 1
xdebug.remote_connect_back => 0 => 0
xdebug.remote_mode => req => req
xdebug.idekey => hantaohuang => hantaohuang`

**Comment by huanghantao** [comment]
你要配置`interpreter options`才行,否则,默认会走xdebug的配置.

![image](https://user-images.githubusercontent.com/22836925/128441693-aec80716-dcd1-4fbd-b1d0-b7727e7e487f.png)


![image](https://user-images.githubusercontent.com/22836925/128441708-2a571094-bddd-40a0-92f8-285d13597f4c.png)

**Comment by YangHuiFor** [comment]
@huanghantao 需要配置哪些参数， 贴出来呗

**Comment by YangHuiFor** [comment]
@huanghantao  我在hyperf框架下PHPunit. 还是不行。大佬求赐教
`interpreter options`
![image](https://user-images.githubusercontent.com/4995476/129186667-97f5cfd7-5702-46a4-9007-87171df1c597.png)
![image](https://user-images.githubusercontent.com/4995476/129186819-8df67232-22db-4c44-bd5f-47496dc1d906.png)
![image](https://user-images.githubusercontent.com/4995476/129186843-8d68d5bb-fa0a-4815-9ce5-aaba49ac8bb4.png)

**Comment by huanghantao** [comment]
加我微信codinghuang



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月12日(周四) 晚上7:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [swoole/yasd] PHPstorm下单元测试如何进行debug (#142)




 
@huanghantao  我在hyperf框架下PHPunit. 还是不行。大佬求赐教
 interpreter options
 
 
 
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
