### ISSUE TITLE
PhpStorm中结束调试时PHP进程没有结束

### ISSUE THREAD

**Issue by drsanwujiang** [swoole/yasd#143]
PhpStorm中结束调试经常出现PHP进程没有结束的情况（设定了监听信号），请问有什么好的解决方法吗？

这个问题貌似之前sdebug也常出现。

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
