### ISSUE TITLE
PHPSTROM调试碰到多维数组会停止debug

### ISSUE THREAD

**Issue by season886** [swoole/yasd#144]
用PHPSTROM调试的时候展开数组，因为数组层级比较多，每当展开第三个层级的时候就停止了debug了，不知道是崩溃了还是怎样
![image](https://user-images.githubusercontent.com/18523125/128991285-20cc2e53-145a-4055-b356-8bba30a07bb7.png)
当点击children那个节点必退

**Comment by season886** [comment]
我把数组转成json了，你恢复一下试试
`[{"id":8753817997219307,"pid":0,"process_name":"\u8bbe\u8ba1\u90e8\u8d1f\u8d23","leaf":false,"children":[{"id":5234755949576894,"pid":8753817997219307,"process_name":"\u8bbe\u8ba1\u5e08","leaf":true},{"id":7099635737011508,"pid":8753817997219307,"process_name":"\u8bbe\u8ba1\u56fe\u7a3f\u5b8c\u6210\u65f6\u95f4","leaf":false,"children":[{"id":5408080341846492,"pid":7099635737011508,"process_name":"\u8bbe\u8ba1\u7a3f\u5f00\u59cb\u65f6\u95f4","leaf":true},{"id":6440935433302412,"pid":7099635737011508,"process_name":"\u8bbe\u8ba1\u7a3f\u622a\u7a3f\u65f6\u95f4","leaf":true},{"id":3111738710975102,"pid":7099635737011508,"process_name":"\u5370\u7ee3\u82b1\/\u5339\u88c5\u5b8c\u6210\u65f6\u95f4","leaf":true},{"id":8200026605470174,"pid":7099635737011508,"process_name":"\u5b9e\u9645\u4ea4\u7a3f\u65f6\u95f4","leaf":true},{"id":1710194808711349,"pid":7099635737011508,"process_name":"\u5dee\u5f02","leaf":true}]}]}]`

**Comment by anhoder** [comment]
+1

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
