### ISSUE TITLE
Breakpoint not working on windows

### ISSUE THREAD

**Issue by mayowa-ola** [swoole/yasd#145]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provides a simple script and debug step to reproduce the problem.

I have the below code in my docker file:
RUN echo "zend_extension=yasd" >> /usr/local/etc/php/conf.d/docker-php-ext-yasd.ini \
    && echo "yasd.debug_mode=remote" >> /usr/local/etc/php/conf.d/docker-php-ext-yasd.ini \
    && echo "yasd.remote_host=172.17.0.1" >> /usr/local/etc/php/conf.d/docker-php-ext-yasd.ini \
    && echo "yasd.remote_port=9001" >> /usr/local/etc/php/conf.d/docker-php-ext-yasd.ini   \
    && echo "yasd.log_level=0" >> /usr/local/etc/php/conf.d/docker-php-ext-yasd.ini

2. What did you expect to see?
I expected to see yasd running with swoole

3. What did you see instead?

16b276aa792ff747f0a1e91483bbe <

[yasd] Connection refused
Swoole is running at 0.0.0.0:80, in /var/www

4. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
I'm running Docker on windows

Linux 3003d92c0967 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux

PHP 8.0.6 (cli) (built: May 12 2021 12:47:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.6, Copyright (c) Zend Technologies
    with Yasd v0.3.8, Our Copyright, by codinghuang

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)

**Comment by huanghantao** [comment]
Can consider to use swoole  https://github.com/swoole/swoole-src/tree/support-xdebug

You can use xdebug directly, as long as the PHP version is 8.1 or greater
