### ISSUE TITLE
phpstorm 中 调试 hyperf 切换 debug 监听开关，会无法捕获debug 信息

### ISSUE THREAD

**Issue by wxfjamdc** [swoole/yasd#147]
重现方式
1、先开启 PhpStorm listen 开关
2、php -e bin/hyperf.php start 启动正常
3、正常触发断点
4、关闭 listen 开关，再次开启
5、无法捕获 debug 信息

------------
再次尝试，发现只有在项目启动前开启 listen 才能捕获。

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
