### ISSUE TITLE
PHPSTORM + WSL2 调试Hyperf 出现swoole报错

### ISSUE THREAD

**Issue by coding-linheng** [swoole/yasd#149]
![QQ截图20210904192557](https://user-images.githubusercontent.com/22805416/132092811-6c4ced4f-666a-4380-888a-1c360c37898f.png)

正常命令行启动可以断点，用postman调试接口时会出现报错
![image](https://user-images.githubusercontent.com/22805416/132092853-15d61fb7-b071-4a0b-9c3c-dde292693c0c.png)
![image](https://user-images.githubusercontent.com/22805416/132092855-afb189ae-a6b9-4ee4-8ce6-a6cabe1b9a4e.png)

接口请求报错如下
![image](https://user-images.githubusercontent.com/22805416/132092882-c889bacc-37f6-40d8-b304-a15c94e049bf.png)
断点是打在代理类中

**Comment by woainixyz1** [comment]
![image](https://user-images.githubusercontent.com/22805416/132125267-b384eed9-bd47-47c1-81d0-d9e681f198c5.png)

**Comment by woainixyz1** [comment]
hyperf版本2.2
![image](https://user-images.githubusercontent.com/22805416/132128973-8f1a9083-d4f6-4f88-8b8e-f6339d34ccaa.png)

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
