### ISSUE TITLE
Using environment variables to set/redefine ini params

### ISSUE THREAD

**Issue by lanfix** [swoole/yasd#150]
Hello. How I can use environment variables to set `remote_host` like in `xdebug`?

```
XDEBUG_CONFIG: "remote_host=172.26.112.1"
```

Or this feature are not available in `yasd`?

**Comment by huanghantao** [comment]
Not currently supported

**Comment by bumbummen99** [comment]
https://www.php.net/manual/en/configuration.file.php#example-36

**Comment by huanghantao** [comment]
Can consider to use swoole https://github.com/swoole/swoole-src/tree/support-xdebug

You can use xdebug directly, as long as the PHP version is 8.1 or greater
