### ISSUE TITLE
唤起PHPSTORM的DEBUG视窗后，无法进行调试

### ISSUE THREAD

**Issue by RodyTime** [swoole/yasd#151]
+ 在linux机器上，安装好yasd之后，可以使用remote模式，在linux本机上的phpstorm进行调试
但是不能在同一个局域网的其他某机器(windows)上进行调试，已知确保了IP与端口正确，且每次运行php -e test.php 可以正常调起 局域网内其他某机器(windows)上的debug,但是不能正常调试

+ 点击Debugger  可以看到如下信息：
cannot find file 'path to test.php' locally
to fix it set server name by environment variable PHP_IDE_CONFIG and restart debug session
还有$_SERVER的全局环境变量

+ 现象 从linux上调起windows上debug视窗后，脚本会阻塞，点击windos上运行程序按钮，linux上脚本会完成运行

+ 尝试过以下处理方式：
命令行设置环境变量  set PHP_IDE_CONFIG=serverName=test
并且在设置中的PHP -> Servers 下添加了一个server  名为test 并设定映射。
重试，无任何变化

+ PHP 版本 7.4

+ 其他信息：昨天第一次配置完毕的时候，是可以调试的，可是后面又不行了。

+ 不知道和是否使用ftp有关？将本地windows文件和linux上文件保持一致的方式，是使用git还是ftp,这个有影响吗？

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
