### ISSUE TITLE
[yasd] recv command error, connection closed

### ISSUE THREAD

**Issue by accountYwz** [swoole/yasd#152]
![image](https://user-images.githubusercontent.com/49814620/136578804-57b1bce8-d5b0-48a7-8f9a-50c155a05018.png)

![image](https://user-images.githubusercontent.com/49814620/136578922-d758a0f2-4d51-472b-a68b-2cabc42a3282.png)
这是啥问题？麻烦请指教

**Comment by idxdy** [comment]
尝试 SCAN_CACHEABLE=true

**Comment by liuhengbo** [comment]
在开发环境下修改代码比较多，这个值需要设置成false，而yasd又需要这个值设置为true，有什么更好的解决办法吗

![image](https://user-images.githubusercontent.com/34394313/148040021-6049c8e3-0f8e-48ef-837a-c2431d637147.png)

**Comment by idxdy** [comment]
没有

**Comment by dmitryuk** [comment]
The same issue with Symfony Framework.

**Comment by izhangxm** [comment]
同样的问题，thinkphp6

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
