### ISSUE TITLE
"php -e" causes segmentation fault

### ISSUE THREAD

**Issue by marko-ilic** [swoole/yasd#154]
When php script with the code for creating swoole server is run with `php`, everything works fine (except yasd), but if the script is run with option -e (`php -e`) segmentation fault will be returned.

Swoole version: 4.8.0

OS: 5.10.47-linuxkit x86_64 Linux
gcc version 10.3.1 20210424 (Alpine 10.3.1_git20210424)
PHP 8.0.11

How to reproduce:
index.php file
```php
<?php 

// ...

$server = new  Swoole\Http\Server("127.0.0.1", 9501);

$server->on("start", function (Server $server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$server->on("request", function (Request $request, Response $response) {
    $response->header("Content-Type", "text/plain");
    $response->end("Hello World\n");
});

$server->start();
```
run the script with `php -e index.php`

output: Segmentation fault

yasd is installed with
```bash
git clone https://github.com/swoole/yasd.git \
    && cd yasd \
    && /usr/local/bin/phpize --clean \
    && /usr/local/bin/phpize \
    && ./configure \
    && make clean \
    && make \
    && make install
```

`php -m`
```
...
Yasd
...
```

**Comment by feelec-yishu** [comment]
I don't want to install blackfilre. As long as I start yasd and run php -e, a segmentation fault (core dumped) will appear

**Comment by huanghantao** [comment]
Can consider to use swoole https://github.com/swoole/swoole-src/tree/support-xdebug

You can use xdebug directly, as long as the PHP version is 8.1 or greater
