### ISSUE TITLE
deepin环境phpstorm+yasd+swoole4.7.1调试报错

### ISSUE THREAD

**Issue by fpysky** [swoole/yasd#157]
环境
操作系统：deepin 社区版 20.2.3
php: 7.4.23
swoole: 4.7.1
php框架：hyperf 2.2
yasd:0.3.9-alpha
![image](https://user-images.githubusercontent.com/40625501/146305797-3e3d18d1-5b8e-4a8c-8a8a-9be97ad7e1aa.png)
![image](https://user-images.githubusercontent.com/40625501/146306121-f394c902-fe87-4484-87f3-e7a6bb01941f.png)
![image](https://user-images.githubusercontent.com/40625501/146306273-847e58b7-b69c-41fa-b00a-e80c0e0e9678.png)

![image](https://user-images.githubusercontent.com/40625501/146305871-6a76f1d1-ffe8-4cca-8350-ed2415457a1e.png)

**Comment by jeristiano** [comment]
这个问题可能是你开启了多个swoole task worker 导致的,应该先确保  server.php  内 `Constant::OPTION_WORKER_NUM => 1`

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
