### ISSUE TITLE
Mac M1Pro 芯片编译成功yasd后，开启扩展失败

### ISSUE THREAD

**Issue by lisiao** [swoole/yasd#158]
环境： php7.4.26
编译安装完yasd扩展后报错。
➜  yasd git:(master) ✗ php74 -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'yasd.so' (tried: /opt/homebrew/lib/php/pecl/20190902/yasd.so (dlopen(/opt/homebrew/lib/php/pecl/20190902/yasd.so, 0x0009): tried: '/opt/homebrew/lib/php/pecl/20190902/yasd.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/yasd.so' (no such file), '/usr/lib/yasd.so' (no such file)), /opt/homebrew/lib/php/pecl/20190902/yasd.so.so (dlopen(/opt/homebrew/lib/php/pecl/20190902/yasd.so.so, 0x0009): tried: '/opt/homebrew/lib/php/pecl/20190902/yasd.so.so' (no such file), '/usr/local/lib/yasd.so.so' (no such file), '/usr/lib/yasd.so.so' (no such file))) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'yasd.so' (tried: /opt/homebrew/lib/php/pecl/20190902/yasd.so (dlopen(/opt/homebrew/lib/php/pecl/20190902/yasd.so, 0x0009): tried: '/opt/homebrew/lib/php/pecl/20190902/yasd.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/yasd.so' (no such file), '/usr/lib/yasd.so' (no such file)), /opt/homebrew/lib/php/pecl/20190902/yasd.so.so (dlopen(/opt/homebrew/lib/php/pecl/20190902/yasd.so.so, 0x0009): tried: '/opt/homebrew/lib/php/pecl/20190902/yasd.so.so' (no such file), '/usr/local/lib/yasd.so.so' (no such file), '/usr/lib/yasd.so.so' (no such file))) in Unknown on line 0
PHP 7.4.26 (cli) (built: Nov 28 2021 14:13:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.26, Copyright (c), by Zend Technologies

PHP 8.1.0同样会报错误。

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
