### ISSUE TITLE
Hyper2.2框架

### ISSUE THREAD

**Issue by laohekou** [swoole/yasd#159]
[yasd] recv command error, connection closed
[yasd] recv command error, Connection reset by peer
[2022-01-11 10:10:16 $81296.0]	WARNING	Server::check_worker_exit_status(): worker(pid=81314, id=9) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.8.5, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
GCC_VERSION: Apple LLVM 13.0.0 (clang-1300.0.29.3)
PHP_VERSION : 7.4.25

[INFO] Worker#9 started.

**Comment by 18310691938** [comment]
我也是这样

**Comment by tw2066** [comment]
一样的

**Comment by 18310691938** [comment]
我的解决了，写了篇文章，可以看一下是否有没注意的步骤；https://learnku.com/articles/64503

**Comment by shaofan7** [comment]
> > 我的解决了，写了篇文章，可以看一下是否有没注意的步骤；https://learnku.com/articles/64503

看了你的文章  ，还是一样的额报错，  server.php  Constant::OPTION_WORKER_NUM => 1,设置也没用
> `[yasd] recv command error, connection closed
[yasd] recv command error, connection closed
[2022-02-27 22:47:39 $24411.0]  WARNING Server::check_worker_exit_status(): worker(pid=24537, id=0) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.8.5, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64
GCC_VERSION: 4.8.5 20150623 (Red Hat 4.8.5-44)
OPENSSL_VERSION: OpenSSL 1.0.2u  20 Dec 2019
PHP_VERSION : 7.4.27
`

**Comment by jeristiano** [comment]
> > > 我的解决了，写了篇文章，可以看一下是否有没注意的步骤；https://learnku.com/articles/64503
> 
> 看了你的文章 ，还是一样的额报错， server.php Constant::OPTION_WORKER_NUM => 1,设置也没用
> 
> > `[yasd] recv command error, connection closed
> > [yasd] recv command error, connection closed
> > [2022-02-27 22:47:39 $24411.0]  WARNING Server::check_worker_exit_status(): worker(pid=24537, id=0) abnormal exit, status=0, signal=11
> > A bug occurred in Swoole-v4.8.5, please report it.
> > The Swoole developers probably don't know about it,
> > and unless you report it, chances are it won't be fixed.
> > You can read How to report a bug doc before submitting any bug reports:
> > > https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
> > > Please do not send bug reports in the mailing list or personal letters.
> > > The issue page is also suitable to submit feature requests.
> 
> OS: Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GCC_VERSION: 4.8.5 20150623 (Red Hat 4.8.5-44) OPENSSL_VERSION: OpenSSL 1.0.2u 20 Dec 2019 PHP_VERSION : 7.4.27 `

我也是在WSL2环境下尝试使用yasd
我的错误是:　[yasd] recv command error, Connection reset by peer
尝试了很多方法，终究不知道是什么原因导致不能用

**Comment by liuende501** [comment]
我试了下配置 SCAN_CACHEABLE=(true) 好像可以

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
