### ISSUE TITLE
Disable yasd using cli

### ISSUE THREAD

**Issue by dmitryuk** [swoole/yasd#160]
I have different environments (dev, sandbox and etc) and want to run Swoole with or without "yasd.enabled=0" flag.
Xdebug provides changing variables on runtime:

`php -dxdebug.enabled=0 ./bin/server`

I have tried `php -i -dyasd.enabled=0` without success. 

Any ways to disable yasd dynamic?

**Comment by huanghantao** [comment]
yasd is disable by default
