### ISSUE TITLE
请问下怎么解决单元测试覆盖率问题

### ISSUE THREAD

**Issue by Moln** [swoole/yasd#173]
之前用 sdebug还能解决配合 phpunit 出单元测试覆盖率报告，yasd似乎没这能力。
PHP 8.0之后的项目，都没办法了

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1

**Comment by Moln** [comment]
分支不存在

**Comment by huanghantao** [comment]
> > 可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug 可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
> 
> @huanghantao `support-xdebug` 分支不存在

已经合并进入了master分支

**Comment by huanghantao** [comment]
> > 已经合并进入了master分支
> 
> 还没发布 release 版本吗?

还没
