### ISSUE TITLE
Can not check the value of static variables in a class

### ISSUE THREAD

**Issue by gitHusband** [swoole/yasd#175]
For example,
```
class Context
{
    protected static $pool = [];
}
```

I can not check the value of self::$pool in VSCODE.

**Comment by huanghantao** [comment]
可以考虑PHP升级后使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
