### ISSUE TITLE
Undefined constant "this" in yasd://debug-eval:1

### ISSUE THREAD

**Issue by mrAndersen** [swoole/yasd#178]
1. What did you do? If possible, provides a simple script and debug step to reproduce the problem.
Using debug in PhpStorm

2. What did you expect to see?
No errors

3. What did you see instead?
Error

4. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Using docker alpine on top of arch linux 6.0.9 host machine, php 8.1.2 inside docker, yasd 0.3.9-alpha

After yasd and phpstorm connection established, after 1 "Step to next line" or 2 calls i am getting error Undefined constant "this" in yasd://debug-eval:1 and forcing to restart whole swoole application

**Comment by shixinzi** [comment]
I also encountered this problem, there are a lot of pit

**Comment by huanghantao** [comment]
In php8.1, Swoole can support Xdebug directly, maybe I can support it over the weekend

**Comment by huanghantao** [comment]
@mrAndersen you can use this branch: 
https://github.com/swoole/swoole-src/tree/support-xdebug
https://github.com/swoole/swoole-src/pull/4915

it can use xdebug directly without yasd.

**Comment by mrAndersen** [comment]
@huanghantao thx, will try

**Comment by huanghantao** [comment]
> @huanghantao thx, will try
> 
> UPD. Can confirm that xdebug works with swoole from https://github.com/swoole/swoole-src/tree/support-xdebug and php 8.1

I have no problem testing. You can test it.
