### ISSUE TITLE
大佬 这个报错啥原因呢 

### ISSUE THREAD

**Issue by shixinzi** [swoole/yasd#179]
[yasd] recv command error, connection closed
WARNING	Server::check_worker_exit_status(): worker(pid=42138, id=0) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.8.9, please report it.
PHP_VERSION : 8.0.18

**Comment by huanghantao** [comment]
可以考虑PHP升级后使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
