### ISSUE TITLE
centos7系统下php8.2.4 make 报错

### ISSUE THREAD

**Issue by coolbosyen** [swoole/yasd#188]
/yasd-0.3.9/src/base.cc: 在函数‘void execute_init_file()’中:
/yasd-0.3.9/src/base.cc:50:26: 错误：不能在赋值时将‘char*’转换为‘zend_string* {aka _zend_string*}’
     file_handle.filename = YASD_G(init_file);
                          ^
make: *** [src/base.lo] 错误 1

**Comment by huanghantao** [comment]
php 8.2直接使用xdebug吧，swoole升级到 5.0.2+
