### ISSUE TITLE
 'zend_string *' (aka '_zend_string *') from 'char *'

### ISSUE THREAD

**Issue by 21307369** [swoole/yasd#189]
系统：mac sonama 14.3.1
PHP version : 8.3.3

yasd-0.3.9/src/base.cc:50:28: error: incompatible pointer types assigning to 'zend_string *' (aka '_zend_string *') from 'char *'
    file_handle.filename = YASD_G(init_file);
                           ^~~~~~~~~~~~~~~~~
./php_yasd.h:53:19: note: expanded from macro 'YASD_G'
#define YASD_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(yasd, v)
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/EServer/software/php/php-8.3.3/include/php/Zend/zend_API.h:270:54: note: expanded from macro 'ZEND_MODULE_GLOBALS_ACCESSOR'
#define ZEND_MODULE_GLOBALS_ACCESSOR(module_name, v) (module_name##_globals.v)
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [src/base.lo] Error 1

**Comment by huanghantao** [comment]
php 8.3直接使用xdebug吧，swoole升级到 5.0.2+
