### ISSUE TITLE
Mac环境下编译报错

### ISSUE THREAD

**Issue by lamplife** [swoole/yasd#25]
**下载的源码编译报错：**

/usr/local/Cellar/php@7.2/7.2.20/include/php/Zend/zend_extensions.h:56:33: note: expanded from macro 'ZEND_EXTENSION_BUILD_ID'
#define ZEND_EXTENSION_BUILD_ID "API" ZEND_TOSTR(ZEND_EXTENSION_API_NO) ZEND_BUILD_TS ZEND_BUILD_DEBUG ZEND_BUILD_SYSTEM ZEND_BUILD_EXTRA
                                ^
/php-extension/yasd/yasd.cc:212:5: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    "Yasd",
    ^
/php-extension/yasd/yasd.cc:213:5: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    PHP_YASD_VERSION,
    ^
././php_yasd.h:25:26: note: expanded from macro 'PHP_YASD_VERSION'
#define PHP_YASD_VERSION "0.1.0"
                         ^
/php-ext/ensionyasd/yasd.cc:214:5: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    "codinghuang",
    ^
/php-extension/yasd/yasd.cc:215:5: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    "https://github.com/huanghantao",
    ^
/php-extension/yasd/yasd.cc:216:5: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    "Our Copyright",

......

yasd/src/cmder_debugger.cc:24:10: fatal error: 'thirdparty/boost/algorithm/include/boost/algorithm/string.hpp' file not found
#include "thirdparty/boost/algorithm/include/boost/algorithm/string.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [src/cmder_debugger.lo] Error 1

**Comment by sy-records** [comment]
git submodule update --init 执行了吗

**Comment by lamplife** [comment]
> git submodule update --init 执行了吗

这一步漏了，在执行，更新很慢，等更新完了我再试试

**Comment by lamplife** [comment]
> > git submodule update --init 执行了吗
> 
> 这一步漏了，在执行，更新很慢，等更新完了我再试试


yasd

Yasd => enabled
Author => codinghuang <codinghuang@qq.com>
Version => 0.1.0
Built => Dec 16 2020 10:57:50

Directive => Local Value => Master Value
yasd.breakpoints_file => .breakpoints_file.log => .breakpoints_file.log
yasd.debug_mode => cmd => cmd
yasd.remote_host => 127.0.0.1 => 127.0.0.1
yasd.remote_port => 9000 => 9000
yasd.depth => 1 => 1

可以了，多谢大佬指点！

**Comment by huanghantao** [comment]
> > git submodule update --init 执行了吗
> 
> 这一步漏了，在执行，更新很慢，等更新完了我再试试

我自己从头到尾试了下，确实下载子模块巨慢无比，我们考虑移除`boost`库
