### ISSUE TITLE
MacOS 下 phpize 报错

### ISSUE THREAD

**Issue by teg1c** [swoole/yasd#31]
`autoheader: error: AC_CONFIG_HEADERS not found in configure.ac`

**Comment by huanghantao** [comment]
能否提供一下完整的输出信息？

**Comment by teg1c** [comment]
@huanghantao 
```
$ phpize --clean && \
phpize && \
./configure && \
make clean && \
make && \
make install
Cleaning..
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
autoheader: error: AC_CONFIG_HEADERS not found in configure.ac
```

**Comment by huanghantao** [comment]
你是否安装了多个`PHP`版本呢？

**Comment by teg1c** [comment]
> 你是否安装了多个`PHP`版本呢？

没有

**Comment by huanghantao** [comment]
你的环境是什么？是在虚拟机里面执行的吗？

**Comment by teg1c** [comment]
> 你的环境是什么？是在虚拟机里面执行的吗？

macOS 宿主机

**Comment by huanghantao** [comment]
今天在安装其他扩展的时候也遇到过执行`phpize`失败的情况。大概是，之前用其他版本的`php`安装过这个扩展，然后换了一个`PHP`版本，然后执行`phpize`就失败了。并且，后一个`php`的`phpize --clean`命令无法清理干净上一个版本的`PHP`生成的`configure`文件，所以一直`phpize`失败。因此，需要手动删除`configure文件`:

```bash
rm configure*
```

**Comment by bigjoehuang** [comment]
安装了多个PHP版本，有php7.4和php8.1， 出现同样问题，无法解决。

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
