### ISSUE TITLE
mac php7.2.33      php -e bin/hyperf.php start 报错 86691 segmentation fault 

### ISSUE THREAD

**Issue by ice-leng** [swoole/yasd#33]
➜  ~ php -v 
PHP 7.2.33 (cli) (built: Aug  7 2020 18:28:03) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.33, Copyright (c) 1999-2018, by Zend Technologies
    with Yasd v0.1.0, Our Copyright, by codinghuang

➜  ~ php --ri yasd

yasd

Yasd => enabled
Author => codinghuang <codinghuang@qq.com>
Version => 0.1.0
Built => Dec 17 2020 17:35:30

Directive => Local Value => Master Value
yasd.breakpoints_file => no value => no value
yasd.debug_mode => remote => remote
yasd.remote_host => 127.0.0.1 => 127.0.0.1
yasd.remote_port => 9000 => 9000
yasd.depth => 1 => 1

执行
✗ php -e bin/hyperf.php start
[1]    86691 segmentation fault  php -e bin/hyperf.php start

**Comment by xtp2217866847** [comment]
我的是这个报错 Connection Failed: Connection refused

**Comment by xtp2217866847** [comment]
我的配置和上面的一样但是用的是hyperf的docker镜像，phpstorm监听也开启了，但是一直是Connection refused

**Comment by huanghantao** [comment]
请用tcpdump等抓包工具抓取9000端口的包，看看网络是否通。你可以把抓到的包贴出来



---原始邮件---
发件人: "xtp2217866847"<notifications@github.com&gt;
发送时间: 2020年12月17日(周四) 晚上9:19
收件人: "swoole/yasd"<yasd@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [swoole/yasd] mac php7.2.33      php -e bin/hyperf.php start 报错 86691 segmentation fault  (#33)




 
我的配置和上面的一样但是用的是hyperf的docker镜像，phpstorm监听也开启了，但是一直是Connection refused

**Comment by sy-records** [comment]
先安装boost依赖。

**Comment by tw2066** [comment]
```
root@WIN-RJACNS8A7VM:/mnt/d/WWW/hf20# apt-get install libboost-all-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libboost-all-dev is already the newest version (1.65.1.0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 230 not upgraded.

root@WIN-RJACNS8A7VM:/mnt/d/WWW/hf20# php --ri yasd

yasd

Yasd => enabled
Author => codinghuang <codinghuang@qq.com>
Version => 0.1.0
Built => Dec 17 2020 19:24:58

Directive => Local Value => Master Value
yasd.breakpoints_file => no value => no value
yasd.debug_mode => remote => remote
yasd.remote_host => 127.0.0.1 => 127.0.0.1
yasd.remote_port => 8000 => 8000
yasd.depth => 1 => 1

root@WIN-RJACNS8A7VM:/mnt/d/WWW/hf20# php -v
PHP 7.2.19 (cli) (built: Jun 23 2019 10:08:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Yasd v0.1.0, Our Copyright, by codinghuang

root@WIN-RJACNS8A7VM:/mnt/d/WWW/hf20# php -e bin/hyperf.php start
Segmentation fault (core dumped)
```

启动不了

**Comment by xtp2217866847** [comment]
> 请用tcpdump等抓包工具抓取9000端口的包，看看网络是否通。你可以把抓到的包贴出来
> […](#)
> ---原始邮件--- 发件人: "xtp2217866847"<notifications@github.com&gt; 发送时间: 2020年12月17日(周四) 晚上9:19 收件人: "swoole/yasd"<yasd@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [swoole/yasd] mac php7.2.33 php -e bin/hyperf.php start 报错 86691 segmentation fault (#33) 我的配置和上面的一样但是用的是hyperf的docker镜像，phpstorm监听也开启了，但是一直是Connection refused — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我现在已经不会出现Connection refused，但是运行的时候没有任何输出，而且也不报错，不知道是不是我的docker是Alpine的原因，我用的apk add boost-dev来安装boost，不知道有没有关系

**Comment by huanghantao** [comment]
> > 请用tcpdump等抓包工具抓取9000端口的包，看看网络是否通。你可以把抓到的包贴出来
> > […](#)
> > ---原始邮件--- 发件人: "xtp2217866847"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年12月17日(周四) 晚上9:19 收件人: "swoole/yasd"<[yasd@noreply.github.com](mailto:yasd@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: Re: [swoole/yasd] mac php7.2.33 php -e bin/hyperf.php start 报错 86691 segmentation fault (#33) 我的配置和上面的一样但是用的是hyperf的docker镜像，phpstorm监听也开启了，但是一直是Connection refused — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 我现在已经不会出现Connection refused，但是运行的时候没有任何输出，而且也不报错，不知道是不是我的docker是Alpine的原因，我用的apk add boost-dev来安装boost

容器里面目前还未测试到，我后续修复一下。

**Comment by xtp2217866847** [comment]
> > > 请用tcpdump等抓包工具抓取9000端口的包，看看网络是否通。你可以把抓到的包贴出来
> > > […](#)
> > > ---原始邮件--- 发件人: "xtp2217866847"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年12月17日(周四) 晚上9:19 收件人: "swoole/yasd"<[yasd@noreply.github.com](mailto:yasd@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: Re: [swoole/yasd] mac php7.2.33 php -e bin/hyperf.php start 报错 86691 segmentation fault (#33) 我的配置和上面的一样但是用的是hyperf的docker镜像，phpstorm监听也开启了，但是一直是Connection refused — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 我现在已经不会出现Connection refused，但是运行的时候没有任何输出，而且也不报错，不知道是不是我的docker是Alpine的原因，我用的apk add boost-dev来安装boost
> 
> 容器里面目前还未测试到，我后续修复一下。

我用phpstorm的时候，IDE里面需要设置 ZendDebugger 的Debug port设置成ini中remote_port端口一致, remote_host要设置宿主机的ip才能通信，希望到时候文档能详细一些方便大家使用

**Comment by huanghantao** [comment]
> > > > 请用tcpdump等抓包工具抓取9000端口的包，看看网络是否通。你可以把抓到的包贴出来
> > > > […](#)
> > > > ---原始邮件--- 发件人: "xtp2217866847"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年12月17日(周四) 晚上9:19 收件人: "swoole/yasd"<[yasd@noreply.github.com](mailto:yasd@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: Re: [swoole/yasd] mac php7.2.33 php -e bin/hyperf.php start 报错 86691 segmentation fault (#33) 我的配置和上面的一样但是用的是hyperf的docker镜像，phpstorm监听也开启了，但是一直是Connection refused — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > 
> > > 
> > > 我现在已经不会出现Connection refused，但是运行的时候没有任何输出，而且也不报错，不知道是不是我的docker是Alpine的原因，我用的apk add boost-dev来安装boost
> > 
> > 
> > 容器里面目前还未测试到，我后续修复一下。
> 
> 我用phpstorm的时候，IDE里面需要设置 ZendDebugger 的Debug port设置成ini中remote_port端口一致, remote_host要设置宿主机的ip才能通信，希望到时候文档能详细一些方便大家使用

是的，要`ip port`一致。感谢你的建议，我们会慢慢的去完善文档。

**Comment by cpj555** [comment]
本地mac运行遇到类似的问题,不知道是不是配置的不对 视频里面phpstrom那部分没有讲怎么配置 
php -v
PHP 7.4.12 (cli) (built: Oct 29 2020 18:37:21) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Yasd v0.1.0, Our Copyright, by codinghuang
 php --ri yasd

yasd

Yasd => enabled
Author => codinghuang <codinghuang@qq.com>
Version => 0.1.0
Built => Dec 18 2020 16:27:29

Directive => Local Value => Master Value
yasd.breakpoints_file => no value => no value
yasd.debug_mode => remote => remote
yasd.remote_host => 127.0.0.1 => 127.0.0.1
yasd.remote_port => 8000 => 8000
yasd.depth => 1 => 1

![image](https://user-images.githubusercontent.com/19289096/102684180-48e86880-4211-11eb-853a-e969187c1094.png)
![image](https://user-images.githubusercontent.com/19289096/102684205-7f25e800-4211-11eb-9f27-f261c4ba0156.png)
![image](https://user-images.githubusercontent.com/19289096/102684208-8baa4080-4211-11eb-8efa-b576b42973fe.png)

**Comment by euii** [comment]
--- ~ » php -v
PHP 7.4.13 (cli) (built: Dec 18 2020 15:39:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
    with Yasd v0.1.0, Our Copyright, by codinghuang

--- ~ » php --ri yasd

yasd

Yasd => enabled
Author => codinghuang <codinghuang@qq.com>
Version => 0.1.0
Built => Dec 18 2020 17:22:09

Directive => Local Value => Master Value
yasd.breakpoints_file => .breakpoints_file.log => .breakpoints_file.log
yasd.debug_mode => remote => remote
yasd.remote_host => 127.0.0.1 => 127.0.0.1
yasd.remote_port => 8000 => 8000
yasd.depth => 1 => 1

--- PhpstormProjects‹master* M› » php -e bin/hyperf.php start                              
Connection Failed: Connection refused

![image](https://user-images.githubusercontent.com/701552/102708182-0a6bb000-42dc-11eb-9e92-08a4311d4bfa.png)


![image](https://user-images.githubusercontent.com/701552/102708176-f45def80-42db-11eb-97a0-540e92427e85.png)

**Comment by euii** [comment]
> ```
> --- ~ » php -v
> PHP 7.4.13 (cli) (built: Dec 18 2020 15:39:09) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>     with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
>     with Yasd v0.1.0, Our Copyright, by codinghuang
> 
> --- ~ » php --ri yasd
> 
> yasd
> 
> Yasd => enabled
> Author => codinghuang <codinghuang@qq.com>
> Version => 0.1.0
> Built => Dec 18 2020 17:22:09
> 
> Directive => Local Value => Master Value
> yasd.breakpoints_file => .breakpoints_file.log => .breakpoints_file.log
> yasd.debug_mode => remote => remote
> yasd.remote_host => 127.0.0.1 => 127.0.0.1
> yasd.remote_port => 8000 => 8000
> yasd.depth => 1 => 1
> 
> --- PhpstormProjects‹master* M› » php -e bin/hyperf.php start                              
> Connection Failed: Connection refused
> ```
> 
> ![image](https://user-images.githubusercontent.com/701552/102708182-0a6bb000-42dc-11eb-9e92-08a4311d4bfa.png)
> 
> ![image](https://user-images.githubusercontent.com/701552/102708176-f45def80-42db-11eb-97a0-540e92427e85.png)

相同的问题, 用php -e 启动以后出现 Connection Failed: Connection refused

**Comment by sy-records** [comment]
用xdebug那个端口

**Comment by xtp2217866847** [comment]
> yasd.breakpoints_file

ide 不需要设置这个吧yasd.breakpoints_file
电话虫监听记得打开，再看本地的端口有没有启用

**Comment by euii** [comment]
> 用xdebug那个端口

确实可以了, 谢谢, 目前测试的结果是这样的.
1. yasd的端口使用的是xdebug的端口,不是zend_debug的端口,默认9000
2. 使用php -e 启动的模式下, 监听小电话必须打开, 如果不打开就会报 Connection Failed: Connection refused

**Comment by cpj555** [comment]
> 用xdebug那个端口

还是报这个错
![Uploading image.png…]()

**Comment by huanghantao** [comment]
`v0.2.6`版本已经修复。
