### ISSUE TITLE
The problem that is vscode use yasd 

### ISSUE THREAD

**Issue by ray-wish** [swoole/yasd#35]
I install yasd. 
When I reopen my computer, the vscode cannot use yasd.
However, before I reopen the computer, I can use yasd in vscode.
![image](https://user-images.githubusercontent.com/74281171/102569096-c92ea100-411f-11eb-987c-8e96a0f56ede.png)
![image](https://user-images.githubusercontent.com/74281171/102569118-d3e93600-411f-11eb-99e6-f4f71faf7ffb.png)
![image](https://user-images.githubusercontent.com/74281171/102569238-0abf4c00-4120-11eb-992e-e6ecb5097324.png)

PS. I install yasd version 0.2.5, but php --ri yasd show 0.1.0

**Comment by sy-records** [comment]
Any hints? Or check if port 9000 is listening

**Comment by ray-wish** [comment]
Yes, 9000 port is listening.

I think the problem may cause by php-fpm or phpbrew. When I use systemd restart php-fpm, yasd will break.
![image](https://user-images.githubusercontent.com/74281171/102732848-b7930680-4376-11eb-87df-e6abd5ea7956.png)
![image](https://user-images.githubusercontent.com/74281171/102732888-c8dc1300-4376-11eb-90c6-790377036c05.png)
![image](https://user-images.githubusercontent.com/74281171/102732992-0f317200-4377-11eb-98fc-62292654bb56.png)

**Comment by huanghantao** [comment]
@ray-wish Maybe you can set it:

```ini
yasd.remote_port=8000
```

Accordingly, you need to change the ide's listening port to `8000`
