### ISSUE TITLE
Where is breakpoints_file

### ISSUE THREAD

**Issue by ChanJuiHuang** [swoole/yasd#39]
Hi, I want to find the breakpoints_file when I use vscode.
I try to set absolutely path, but I didn't find the file.
Please help me!

This is my set and my folder permission is 777.
`yasd.breakpoints_file="/home/<path>/yasd.log"`

**Comment by huanghantao** [comment]
Hello, there is no support for the specified directory, only in the current directory cache. We will support it in v0.3.0.

**Comment by ChanJuiHuang** [comment]
If I use IDE mode, could I find the break point file?
Thanks!

**Comment by sy-records** [comment]
This file currently only supports cmd mode

**Comment by huanghantao** [comment]
> If I use IDE mode, could I find the break point file?
> Thanks!

I don't think the IDE is necessary to support breakpoint files, because the IDE itself will save the breakpoints.

**Comment by ChanJuiHuang** [comment]
Thanks, I know your logic^^

**Comment by huanghantao** [comment]
Caching breakpoints at specified directory is supported.
