### ISSUE TITLE
FPM下可用吗？

### ISSUE THREAD

**Issue by jobinli** [swoole/yasd#40]
FPM的项目能使用yasd调试吗？

**Comment by huanghantao** [comment]
> FPM的项目能使用yasd调试吗？

理论上是可用的

**Comment by ChanJuiHuang** [comment]
我搭配vscode使用，除錯fpm項目似乎偵測不到斷點。如果我先用xdebug除錯，停用xdebug，再啟用yasd除錯才找的到斷點。重新啟動fpm之後yasd就找不到斷點。
最後還是切回xdebug除錯 XD

**Comment by huanghantao** [comment]
> 我搭配vscode使用，除錯fpm項目似乎偵測不到斷點。如果我先用xdebug除錯，停用xdebug，再啟用yasd除錯才找的到斷點。重新啟動fpm之後yasd就找不到斷點。
> 最後還是切回xdebug除錯 XD

我们会在`v0.3.0`版本对`FPM`进行兼容。

**Comment by huanghantao** [comment]
@jobinli 你可以尝试一下`support-fpm`分支，看看`FPM`下是否可以调试。

**Comment by huanghantao** [comment]
@jobinli 你好，你可以尝试一下`support-fpm`分支，看看`FPM`下是否可以调试。

**Comment by jobinli** [comment]
> @jobinli 你好，你可以尝试一下`support-fpm`分支，看看`FPM`下是否可以调试。

你好，测试了下，没响应断点。

![image](https://user-images.githubusercontent.com/59111601/103130935-ba288f80-46d9-11eb-87e7-aaee1d6ec3bb.png)

**xdebug** 下开启了 `xdebug.start_with_request` 能正常响应。是否缺少类似的配置或者需要配置个 *xdebug_session* 之类的才能触发？ 
![image](https://user-images.githubusercontent.com/59111601/103131395-89e1f080-46db-11eb-9680-284ebe28e7ad.png)

**Comment by huanghantao** [comment]
你试一试`php -S`启动服务呢？

**Comment by jobinli** [comment]
`php -S 127.0.0.1:9000 test.php` ，启动，也是不响应。
`php -e -S 127.0.0.1:9000 test.php`，启动，请求时候报错

```bash
PHP 7.2.34-8+ubuntu18.04.1+deb.sury.org+1 Development Server started at Fri Dec 25 18:15:07 2020
Listening on http://127.0.0.1:9090
Document root is /var/www/html/test
Press Ctrl-C to quit.
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
[1]    11465 abort (core dumped)  php -e -S 127.0.0.1:9090 test.php
```

**Comment by huanghantao** [comment]
这样试试：

```bash
php -e -S 127.0.0.1:9501 -t .
```

**Comment by jobinli** [comment]
> 这样试试：
> 
> ```shell
> php -e -S 127.0.0.1:9501 -t .
> ```

这样运行可以。
![image](https://user-images.githubusercontent.com/59111601/103132024-1beaf880-46de-11eb-8549-c378592f3d0f.png)

**Comment by huanghantao** [comment]
好吧，我修修`bug`。

**Comment by huanghantao** [comment]
@jobinli 你好，`php -S 127.0.0.1:9000 test.php`的方式应该是可以了，你再试试？

**Comment by huanghantao** [comment]
试试`support-fpm`分支最新的代码？应该是可以在`FPM`下调试了。

**Comment by jobinli** [comment]
你好，`php -S 127.0.0.1:9090 test.php` 方式成功。经过nginx代理后 `fpm` 下还不响应断点。打印出的脚本路径也是没问题对应的了。

![image](https://user-images.githubusercontent.com/59111601/103136221-60d05880-46f9-11eb-8140-be9007269ed9.png)

**Comment by jobinli** [comment]
你好，**tcpdump** 在nginx代理形式下没有包抓到。 `php -S` 形式下能抓到。感觉似乎没触发到 **yasd**。

**Comment by huanghantao** [comment]
确认下，`nginx`是否代理到了`FPM`。

**Comment by huanghantao** [comment]
你再更新下`support-fpm`分支试试

**Comment by huanghantao** [comment]
已解决
