### ISSUE TITLE
yasd可以像sdebug一样设置xdebug.idekey吗

### ISSUE THREAD

**Issue by woainixyz1** [swoole/yasd#59]
[xdebug]
zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_host=192.168.1.134
xdebug.remote_port=9000
xdebug.idekey="xdebug"

类似这样设置idekey

**Comment by sy-records** [comment]
yasd用不到这个，有什么需求？

**Comment by woainixyz1** [comment]
因为我是远程服务器调试的，想用ide调试，跟之前sdebug一样直接指定key方便监听断点 
![debug](https://user-images.githubusercontent.com/22805416/103349394-aadd8380-4ad7-11eb-9a20-005a20d42c39.png)

**Comment by woainixyz1** [comment]
sdebug PHP7.4好像用不了，编译的时候会报错，要PHP<7.4

**Comment by huanghantao** [comment]
`yasd`不需要`idekey`。

**Comment by woainixyz1** [comment]
就是服务器调试，我是windows，用的公司的本地服务器

**Comment by huanghantao** [comment]
> 就是服务器调试，我是windows，用的公司的本地服务器

那你配置好`remote_host`和`remote_port`就好。`remote_host`配置成你`IDE`所在的机器的网卡`ip`地址。

**Comment by woainixyz1** [comment]
能给个phpstorm的配置吗，yasd的ide配置不知道怎么设置了，怎么都不能断点

**Comment by sy-records** [comment]
扩展装好，配置填写正确，右上角的电话图标点成绿色
![image](https://user-images.githubusercontent.com/33931153/103390999-30057e80-4b52-11eb-880e-f353f5470b6b.png)

**Comment by woainixyz1** [comment]
配置是这样设置的，sdebug的时候有idekey可以直接调试，用这个时候监听不到  
![debug](https://user-images.githubusercontent.com/22805416/103391213-2af4ff00-4b53-11eb-8380-286af59d1557.png)
![yasd](https://user-images.githubusercontent.com/22805416/103391214-2defef80-4b53-11eb-8548-bff1f9ab73bc.png)

**Comment by huanghantao** [comment]
是否配置了path mapping

**Comment by sy-records** [comment]
php -m , 然后你服务怎么启动的？配置项发下

**Comment by huanghantao** [comment]
`yasd.ini`也提供下

**Comment by woainixyz1** [comment]
![映射](https://user-images.githubusercontent.com/22805416/103391421-6a701b00-4b54-11eb-8195-2a84c31c4417.png)
![yasd](https://user-images.githubusercontent.com/22805416/103391426-6cd27500-4b54-11eb-9c7a-64e79eb5e245.png)
![-m](https://user-images.githubusercontent.com/22805416/103391435-7c51be00-4b54-11eb-9d79-3574b2e56883.png)
直接在服务器 start启动的

**Comment by huanghantao** [comment]
漏了`-e`:

```bash
php -e bin/hyperf.php
```

**Comment by woainixyz1** [comment]
是的是的，谢谢大佬，没有加上-e，万分感谢
