### ISSUE TITLE
是否支持PHPStorm？

### ISSUE THREAD

**Issue by Alion548** [swoole/yasd#6]
能不能和IDE配合实现类似xdebug的可视化Debug功能

**Comment by sy-records** [comment]
后面会支持

**Comment by ray-wish** [comment]
請問有支持vscdeo嗎？感謝^^

**Comment by sy-records** [comment]
一样的，后面都会支持。

**Comment by liuboalex** [comment]
mac上编译报错，环境是7.4.12
![image](https://user-images.githubusercontent.com/6063433/101235925-9b9d2d00-3707-11eb-8239-6717f1c80102.png)

**Comment by huanghantao** [comment]
php的问题，可以忽略。php8已经修复



---原始邮件---
发件人: "liubo"<notifications@github.com&gt;
发送时间: 2020年12月5日(周六) 下午2:39
收件人: "swoole/yasd"<yasd@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [swoole/yasd] 是否支持PHPStorm？ (#6)




 
mac上编译报错，环境是7.4.12

**Comment by huanghantao** [comment]
能否把error地方截图一下？warning可以忽略



---原始邮件---
发件人: "liubo"<notifications@github.com&gt;
发送时间: 2020年12月5日(周六) 下午2:39
收件人: "swoole/yasd"<yasd@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [swoole/yasd] 是否支持PHPStorm？ (#6)




 
mac上编译报错，环境是7.4.12

**Comment by fywtat** [comment]
最新的goland 2020.3出了选择协程调试的功能 可以参考

**Comment by huanghantao** [comment]
> 最新的goland 2020.3出了选择协程调试的功能 可以参考

这个功能我们可以考虑

**Comment by huanghantao** [comment]
已经支持`vscode`，`yasd`配置如下：

```ini
zend_extension=yasd
yasd.debug_mode=remote
yasd.remote_host=127.0.0.1
yasd.remote_port=9000
```

`vscode`的`launch.json`配置如下：

```json
{
    "name": "Listen for XDebug",
    "type": "php",
    "request": "launch",
    "port": 9000
 },
```

**Comment by ChanJuiHuang** [comment]
依據下面圖示設定，使用ide或cmd除錯，只能二者擇其一，不能同時支援ide和cmd除錯對嗎？
![image](https://user-images.githubusercontent.com/12593365/101712173-ea641180-3acf-11eb-91de-02db5302c99f.png)

**Comment by huanghantao** [comment]
> 依據下面圖示設定，使用ide或cmd除錯，只能二者擇其一，不能同時支援ide和cmd除錯對嗎？
> ![image](https://user-images.githubusercontent.com/12593365/101712173-ea641180-3acf-11eb-91de-02db5302c99f.png)

是的

**Comment by huanghantao** [comment]
`phpstorm`已经支持，可以在`feat-phpstorm`分支进行体验。

**Comment by huanghantao** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22836925/101782673-46608180-3b34-11eb-8a83-b5ed6e9dc415.png">
<img width="822" alt="image" src="https://user-images.githubusercontent.com/22836925/101782709-51b3ad00-3b34-11eb-930a-15926f881b5b.png">
<img width="803" alt="image" src="https://user-images.githubusercontent.com/22836925/101782723-54160700-3b34-11eb-8f6f-4e5aa47658c2.png">
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/22836925/101782731-5710f780-3b34-11eb-98bb-43f085875789.png">

**Comment by huanghantao** [comment]
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/22836925/101782882-858ed280-3b34-11eb-8ae5-e6d7c786d028.png">
