### ISSUE TITLE
start 阻塞在这里

### ISSUE THREAD

**Issue by weiba0** [swoole/yasd#61]
![image](https://user-images.githubusercontent.com/37693420/103393081-cf7b3f00-4b5b-11eb-981e-477cc5e528c8.png)

**Comment by weiba0** [comment]
![image](https://user-images.githubusercontent.com/37693420/103393090-e0c44b80-4b5b-11eb-96ba-0b7355b5f730.png)

**Comment by weiba0** [comment]
php -e bin/hyperf.php start  后  阻塞在这里

**Comment by huanghantao** [comment]
> php -e bin/hyperf.php start 后 阻塞在这里

When using yasd, if the framework starts slowly (most of the time it's because the framework is scanning a lot of files), you can execute the following command.

`composer dump-autoload -o`

Then modify the following configuration config/config.php:

'scan_cacheable' => env('SCAN_CACHEABLE', true)

**Comment by weiba0** [comment]
我们已经等待了差不多十分钟了，但是还是没有任何输出

**Comment by huanghantao** [comment]
> 我们已经等待了差不多十分钟了，但是还是没有任何输出

方便加一个微信吗？我的微信：codinghuang

**Comment by huanghantao** [comment]
调试后发现，是`path mapping`没有配置对。
