### ISSUE TITLE
WARNING check_worker_exit_status: worker#27[pid=2546428] abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by coding-linheng** [swoole/yasd#62]
[2020-12-31 11:29:00 $2545105.0] WARNING check_worker_exit_status: worker#27[pid=2546428] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.5.9, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:

https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

用yasd调试启动2.0的时候会有以上报错

**Comment by huanghantao** [comment]
能否截图描述下调试过程？

**Comment by woainixyz1** [comment]
![QQ截图20201231114131](https://user-images.githubusercontent.com/22805416/103393318-06058980-4b5d-11eb-9f1c-994ca164f303.png)
正常启动的话没有这个报错，用php -e bin/hyperf.php start启动的时候会报错，而且项目在ide里监听不到，之前1.1的项目能正常监听试用

**Comment by huanghantao** [comment]
执行下`php --ri yasd`我看看？

**Comment by woainixyz1** [comment]
![Uploading php --ri yasd.png…]()

**Comment by woainixyz1** [comment]
![php --ri yasd](https://user-images.githubusercontent.com/22805416/103393453-a8be0800-4b5d-11eb-9c13-df7a613ce1fb.png)

**Comment by huanghantao** [comment]
能否提供一下`valgrind `的日志？

**Comment by woainixyz1** [comment]
还是用不了，那个日志不知道在哪里= =
现在有新的BUG提示
![BUG8](https://user-images.githubusercontent.com/22805416/103743329-fa233700-5036-11eb-937f-1fcac320469c.png)

**Comment by sy-records** [comment]
看下这里 https://wiki.swoole.com/#/other/issue?id=%e5%85%b3%e4%ba%8e%e6%ae%b5%e9%94%99%e8%af%af%e6%a0%b8%e5%bf%83%e8%bd%ac%e5%82%a8

**Comment by woainixyz1** [comment]
[valgrind.log](https://github.com/swoole/yasd/files/5775083/valgrind.log)
你看看，不行我再运行jiuyidian久一点

**Comment by huanghantao** [comment]
你好，更新下`yasd`的`master`代码试试？看看还有没有这个问题。

**Comment by woainixyz1** [comment]
可以断点了，但是又出新的报错，你们看下
root@ym-X10DAi:/home/share/wwwroot/project-hyperfcms/cms_php# php -e bin/hyperf.php start
start successcURL error 7: Failed to connect to 192.168.1.156 port 7777: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)do doQwxRecvMsg at2021-01-07 10:06:00
do doQwxRecvMsg at2021-01-07 10:07:00
free(): invalid next size (fast)
[2021-01-07 10:07:30 $2269172.0]	WARNING	check_worker_exit_status: worker#1[pid=2269190] abnormal exit, status=0, signal=6
do doQwxRecvMsg at2021-01-07 10:08:00
free(): invalid next size (fast)
[2021-01-07 10:08:09 $2269172.0]	WARNING	check_worker_exit_status: worker#12[pid=2269707] abnormal exit, status=0, signal=6
free(): invalid next size (fast)
[2021-01-07 10:08:30 $2269172.0]	WARNING	check_worker_exit_status: worker#33[pid=2270742] abnormal exit, status=0, signal=6
do doQwxRecvMsg at2021-01-07 10:09:00
double free or corruption (!prev)
[2021-01-07 10:09:00 $2269172.0]	WARNING	check_worker_exit_status: worker#1[pid=2272823] abnormal exit, status=0, signal=6

**Comment by huanghantao** [comment]
加我微信`codinghuang`，我看看什么问题

**Comment by q215613905** [comment]
我也遇到楼上的问题   大兄弟你解决了没有呢

**Comment by liuhengbo** [comment]
我这边是可以进入断点   但3秒钟后就崩溃

报错信息：
[yasd] recv command error, connection closed
[2021-08-19 17:26:30 $41237.0]	WARNING	Server::check_worker_exit_status(): worker(pid=41255, id=12) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.7.0, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.


php --ri yasd


Yasd => enabled
Author => codinghuang <codinghuang@qq.com>
Version => 0.3.9-alpha
Built => Aug 13 2021 20:40:46

Directive => Local Value => Master Value
yasd.breakpoints_file => no value => no value
yasd.debug_mode => remote => remote
yasd.remote_host => 127.0.0.1 => 127.0.0.1
yasd.remote_port => 9999 => 9999
yasd.depth => 1 => 1
yasd.log_level => -1 => -1
yasd.max_executed_opline_num => 0 => 0
yasd.init_file => no value => no value
yasd.open_extended_info => 0 => 0
xdebug.coverage_enable => 1 => 1
xdebug.profiler_enable => 1 => 1
xdebug.remote_autostart => 1 => 1
xdebug.remote_connect_back => 0 => 0
xdebug.remote_mode => req => req
xdebug.idekey => hantaohuang => hantaohuang

swoole 版本：
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.7.0
Built => Aug  7 2021 11:00:16
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144



php -m 扩展


[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
phpdbg_webhelper
posix
pspell
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
swoole
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
yasd
Zend OPcache
zip
zlib

[Zend Modules]
Yasd
Zend OPcache

**Comment by dmitryuk** [comment]
Any updates on it? the same issue

**Comment by faganchalabizada** [comment]
The same error. Do anybody solves?

**Comment by shixinzi** [comment]
The same error. Do anybody solves?  +1

**Comment by huanghantao** [comment]
Can consider to use swoole - xdebug branch of SRC, https://github.com/swoole/swoole-src/tree/support-xdebug

You can use xdebug directly, as long as the PHP version is 8.1 or greater
