### ISSUE TITLE
安装boost后 php运行有点问题

### ISSUE THREAD

**Issue by fywtat** [swoole/yasd#64]
1 brew install boost 
2 php -v
`dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.63.dylib
  Referenced from: /usr/local/Cellar/php@7.2/7.2.15/bin/php
  Reason: image not found
zsh: abort      php -v`

**Comment by huanghantao** [comment]
仅仅是安装一个`boost`库就导致`php`有问题？如果是的话，你估计要把`bug`报给`php-src`。
