### ISSUE TITLE
在phpstorm下关闭调试模式服务器直接502了

### ISSUE THREAD

**Issue by coding-lover** [swoole/yasd#65]
相关版本：
--macos 10.14.6
--phpstorm 2019.3.4
--PHP 7.3.18
--- yasd
`
Yasd => enabled
Author => codinghuang <codinghuang@qq.com>
Version => 0.3.2-alpha
Built => Jan  4 2021 18:52:55

Directive => Local Value => Master Value
yasd.breakpoints_file => no value => no value
yasd.debug_mode => remote => remote
yasd.remote_host => 127.0.0.1 => 127.0.0.1
yasd.remote_port => 9900 => 9900
yasd.depth => 1 => 1
yasd.log_level => -1 => -1
xdebug.coverage_enable => 1 => 1
xdebug.profiler_enable => 1 => 1
xdebug.remote_autostart => 1 => 1
xdebug.remote_connect_back => 0 => 0
xdebug.remote_mode => req => req
`

**开启phpstorm调试模式时，可以正常访问 localhost
但关闭phpstorm调试模式后，再访问就会报下面的错误** 
`
2021/01/04 20:00:00 [error] 215#0: *2291 kevent() reported about an closed connection (54: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: 127.0.0.1, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"

`

**Comment by jobinli** [comment]
因为 **fpm** 下默认是开启了 `yasd` 的调试功能，会去连接指定的调试端口。感觉可以加个类似 `xdebug` 中的 **XDEBUG_SESSION** 功能，来决定是否启用拓展的调试功能。不过这个拓展初衷好像并不是调试 **fpm** 的项目。

**Comment by huanghantao** [comment]
下个版本会去判断是否可以连接上`IDE`，如果连接不上，那么认为不需要调试，让程序继续跑下去。

**Comment by huanghantao** [comment]
你可以尝试一下分支`fix-issue-65`

**Comment by coding-lover** [comment]
插件更新到 fix-issue-65版本了
关闭phpstorm调试模式后
访问 localhost 会偶尔出现
2021/01/05 16:03:24 [error] 27636#0: *4067 kevent() reported about an closed connection (54: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: 127.0.0.1, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"

**Comment by huanghantao** [comment]
能否加一个微信聊聊，我的微信`codinghuang`

**Comment by huanghantao** [comment]
调试后，发现是`PHP`脚本里面调用了函数`date_default_timezone_set('Asia/Shanghai')`导致`cgi`进程挂了。

**Comment by huanghantao** [comment]
解决方法1，设置环境变量`USE_ZEND_ALLOC=0`，例如：

```bash
USE_ZEND_ALLOC=0 php-cgi -b 0.0.0.0:8000
```

**Comment by huanghantao** [comment]
`master`分支已解决。
