### ISSUE TITLE
在swoole alpine镜像中make报错

### ISSUE THREAD

**Issue by jiang-wen** [swoole/yasd#66]
下载了v0.3.2的release，在phpswoole/swoole:4.5.10-php7.3-alpine镜像中 执行apk add boost-dev之后执行docker-php-ext-install报错

如图
![image](https://user-images.githubusercontent.com/21187340/103538082-87984700-4ed0-11eb-8c61-ed69a4534fb8.png)

**Comment by huanghantao** [comment]
`master`已修复。
