### ISSUE TITLE
指定php-config方式编译未能通过

### ISSUE THREAD

**Issue by jobinli** [swoole/yasd#7]
安装了 `php7.2.24` 与 `php7.4.12`

使用7.4对应的 `phpize7.4` 以及在configue时候指定对应php-config，make时候报找不到 `php/main/php.h`

➜  yasd git:(master) phpize7.4 --clean
Cleaning..
➜  yasd git:(master) phpize7.4        
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
➜  yasd git:(master) ./configure --with-php-config=/usr/bin/php-config7.4
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib
checking for PHP extension directory... /usr/lib/php/20190902
checking for PHP installed headers prefix... /usr/include/php/20190902
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable yasd support... yes, shared
checking whether to enable yasd developer build flags... no
checking if compiling with clang... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) nawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
➜  yasd git:(master) make      
/bin/bash /home/jobin/software/yasd/libtool --mode=compile g++  -I. -I/home/jobin/software/yasd -DPHP_ATOM_INC -I/home/jobin/software/yasd/include -I/home/jobin/software/yasd/main -I/home/jobin/software/yasd -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib -I/include  -DHAVE_CONFIG_H  -g -O2 -Wall -Wno-unused-function -Wno-deprecated -Wno-deprecated-declarations -std=c++11   -c /home/jobin/software/yasd/yasd.cc -o yasd.lo 
libtool: compile:  g++ -I. -I/home/jobin/software/yasd -DPHP_ATOM_INC -I/home/jobin/software/yasd/include -I/home/jobin/software/yasd/main -I/home/jobin/software/yasd -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib -I/include -DHAVE_CONFIG_H -g -O2 -Wall -Wno-unused-function -Wno-deprecated -Wno-deprecated-declarations -std=c++11 -c /home/jobin/software/yasd/yasd.cc  -fPIC -DPIC -o .libs/yasd.o
/home/jobin/software/yasd/yasd.cc:28:10: fatal error: php/main/php.h: 没有那个文件或目录
 #include "php/main/php.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
Makefile:192: recipe for target 'yasd.lo' failed
make: *** [yasd.lo] Error 1

**Comment by huanghantao** [comment]
你可以检查下`/usr/include/php/20190902`目录里面有没有丢失的文件。

**Comment by jobinli** [comment]
![image](https://user-images.githubusercontent.com/59111601/101010532-4b09c080-359d-11eb-91c5-bc2af1866c59.png)

`/usr/include/php/20190902` 下，没有 `php` 这个文件夹，只有 `main` 下面有 `php.h`。编译此插件除了需要安装 `php-dev`，还需要其他的？

**Comment by huanghantao** [comment]
> ![image](https://user-images.githubusercontent.com/59111601/101010532-4b09c080-359d-11eb-91c5-bc2af1866c59.png)
> 
> `/usr/include/php/20190902` 下，没有 `php` 这个文件夹，只有 `main` 下面有 `php.h`。编译此插件除了需要安装 `php-dev`，还需要其他的？

你应该是自己手动编译的，你可以在外面套一个`php`目录。

**Comment by jobinli** [comment]
> > ![image](https://user-images.githubusercontent.com/59111601/101010532-4b09c080-359d-11eb-91c5-bc2af1866c59.png)
> > `/usr/include/php/20190902` 下，没有 `php` 这个文件夹，只有 `main` 下面有 `php.h`。编译此插件除了需要安装 `php-dev`，还需要其他的？
> 
> 你应该是自己手动编译的，你可以在外面套一个`php`目录。

`php` 与 `php-dev` 都是通过 `apt` 直接安装的。`Ubantu 18.04`。通过在 `/usr/include/php/20190902` 套多层 `php` 把其他的链接进去的确可以编译成功。

**Comment by huanghantao** [comment]
我不是很清楚ubuntu下你的这种安装方式，我见过的安装方式都是有`php`这个目录的。如果有多人反馈同样的问题，我再去掉`php`目录。

**Comment by zd04** [comment]
我的系统是windows10的WSL环境要报错 
yasd/yasd.cc:28:10: fatal error: php/main/php.h: No such file or directory

**Comment by huanghantao** [comment]
> 我的系统是windows10的WSL环境要报错
> yasd/yasd.cc:28:10: fatal error: php/main/php.h: No such file or directory

看起来不是个例了，那我改改

**Comment by huanghantao** [comment]
已经修改完了，不需要套一个`php`目录了，在`master`分支。
