### ISSUE TITLE
Xdebug protocol support / PHPStorm support

### ISSUE THREAD

**Issue by Rastusik** [swoole/yasd#76]
Is there any roadmap to support PHPStorm? It seems to me that the easiest way without the need for cooperation from Jetbrains (or other IDEs' developers) would be to implement the same protocol as Xdebug does, but I have no idea whether such thing is at least considered. 

Or are there any other considerations how to make Yasd compatible with IDEs? 

This problem currently blocks our migration to PHP 8, which is kind of painful. We would gladly migrate to Yasd after there is support for PHPStorm, but until then it feels like there is no workaround. Terminal debugging is quite user unfriendly compared to PHPStorm. Not every developer has enough experience to use CLI debugging.

Thank you in advance for feedback.

**Comment by Rastusik** [comment]
Oh I just found some info about IDE Support:
```
IDE debug mode

zend_extension=yasd
yasd.debug_mode=remote
yasd.remote_host=127.0.0.1
yasd.remote_port=9000
```

Will this work for PHPStorm?

**Comment by huanghantao** [comment]
yes!



---Original---

**Comment by Rastusik** [comment]
thank you! :) I just found this https://github.com/swoole/yasd/releases/tag/v0.2.0 ... 

BTW maybe it would help to update readme specifically with information about VSCode and PHPStorm support.
