### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by juber-ivre** [swoole/yasd#78]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provides a simple script and debug step to reproduce the problem.

Cloned the repo.

2. What did you expect to see?

Makefile to build solution

3. What did you see instead?
N/A

4. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

I'm unable to follow steps for installation after clone the repo. There's no Makefile.

Any suggestions? 

5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

php -v
PHP 7.3.25 (cli) (built: Dec 17 2020 09:49:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.25, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.25, Copyright (c) 1999-2018, by Zend Technologies
    with Sdebug v2.9.3-dev, Copyright (c) 2002-2020, by Derick Rethans

**Comment by sy-records** [comment]
Did you execute `phpize` and `. /configure` yet?  
https://github.com/swoole/yasd#how-to-use-it

**Comment by juberjj** [comment]
@sy-records  I did, no issues on that but cannot "make" it

**Comment by sy-records** [comment]
Are there any error messages?
You can send me the compilation log

**Comment by huanghantao** [comment]
can you provide the output of phpize and configure？



---Original---

**Comment by juberjj** [comment]
![image](https://user-images.githubusercontent.com/16324958/104707899-f10c2700-5714-11eb-8abc-8c14a6029e49.png)

**Comment by sy-records** [comment]
![image](https://user-images.githubusercontent.com/33931153/104711029-ca251380-575b-11eb-943e-a022e1a50987.png)

You'll need to install the Boost library first.

macOS:
```bash
brew install boost
```
Ubuntu:
```bash
apt-get install libboost-all-dev
```
CentOS:
```bash
yum install boost boost-devel
```

**Comment by juberjj** [comment]
I'm embarrased, missed that. All sorted now guys an that perspective. Let's see if that will work with swoole in my case.

**Comment by juberjj** [comment]
The installation is done 

![image](https://user-images.githubusercontent.com/16324958/104725670-4e5ea300-572a-11eb-9882-3ca35269a0c4.png)


zend_extension=yasd
yasd.debug_mode=remote
yasd.remote_host=127.0.0.1
yasd.remote_port=9000

but not connecting on VsCode

![image](https://user-images.githubusercontent.com/16324958/104725736-66362700-572a-11eb-881e-58c251df9752.png)

**Comment by juber-ivre** [comment]
The issue facing on the title has been resolved, so I'm closing this but open a new one as I'm unable to connect to vscode.
