### ISSUE TITLE
[yasd] Connection refused

### ISSUE THREAD

**Issue by pizsd** [swoole/yasd#84]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provides a simple script and debug step to reproduce the problem.
php -e bin/hyperf.php start 提示
[yasd] Connection refused

![image](https://user-images.githubusercontent.com/53469108/104981411-85db9100-5a43-11eb-814f-75fe8f51bc9a.png)

2. What did you expect to see?

3. What did you see instead?

![image](https://user-images.githubusercontent.com/53469108/104981453-9986f780-5a43-11eb-9c21-f1ce3c877c3a.png)

4. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

![image](https://user-images.githubusercontent.com/53469108/104981508-b6bbc600-5a43-11eb-950b-633e1f9e2625.png)

**Comment by huanghantao** [comment]
你用`nc`命令看看能不能连上

**Comment by pizsd** [comment]
嗯嗯，好了，原因是phpstorm开启监听的时候没起作用，重启ide就好了，多谢大佬
