### ISSUE TITLE
断点有问题

### ISSUE THREAD

**Issue by renf** [swoole/yasd#87]
我 [设置了断点，但是用r就直接运行走了。。
在docker里面运行的fpm
![image](https://user-images.githubusercontent.com/8871261/106453376-30cc6000-64c4-11eb-8108-713e62401321.png)

**Comment by huanghantao** [comment]
你在配置文件里面关掉`xdebug`

**Comment by renf** [comment]
说错了 是7.3.26, 我不知道咋个关😅， 我就是在扩展里面把xdebug改为了xdebug1😅。老师可以加你微信么？

**Comment by renf** [comment]
> 你在配置文件里面关掉`xdebug`
说错了 是7.3.26, 我不知道咋个关😅， 我就是在扩展里面把xdebug改为了xdebug1😅。老师可以加你微信么？

**Comment by huanghantao** [comment]
微信codinghuang

**Comment by huanghantao** [comment]
已解决，没有配置为`zend_extension`。

**Comment by renf** [comment]
=


> 已解决，没有配置为`zend_extension`。

感谢大佬指点
