### ISSUE TITLE
提示 free(): invalid next size (fast) 或者内存溢出

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [swoole/yasd#90]
您好,
我在调试的时候会提示free(): invalid next size (fast) 或者内存溢出,不使用调试的时候程序正常运行
想问下调试的时候怎么设置内存大小呀 或者解决这个问题

**Comment by huanghantao** [comment]
能否提供一份`valgrind`日志？

```bash
USE_ZEND_ALLOC=0 valgrind --trace-children=yes --log-file=valgrind.log php -e xxx.php
```

触发了你这个错误之后，把这个`valgrind.log`文件给我看看。

**Comment by ZhangTianyi-1998** [comment]
[valgrind.log](https://github.com/swoole/yasd/files/5923035/valgrind.log)
您好 这是我的日志  今天运行的时候又出现了corrupted double-linked list 这个问题

**Comment by huanghantao** [comment]
你执行`php -m`我看看。

**Comment by ZhangTianyi-1998** [comment]
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
enchant
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imap
interbase
intl
json
ldap
libxml
mbstring
mysql
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
PDO_Firebird
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
readline
recode
redis
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
sodium
SPL
sqlite3
standard
swoole
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
yasd
Zend OPcache
zip
zlib

[Zend Modules]
Yasd
Zend OPcache

**Comment by huanghantao** [comment]
把`opcache`关掉试试？另外，`yasd`你用的是最新的吗？

**Comment by ZhangTianyi-1998** [comment]
我把cpcache关掉了 重新编译了一个最新的yasd 
root@DESKTOP-CFFM9HI:/etc/php/7.2/cli/conf.d# php --ri yasd

yasd

Yasd => enabled
Author => codinghuang <codinghuang@qq.com>
Version => 0.3.7
Built => Feb  4 2021 16:17:33

Directive => Local Value => Master Value
yasd.breakpoints_file => no value => no value
yasd.debug_mode => remote => remote
yasd.remote_host => 192.168.1.125 => 192.168.1.125
yasd.remote_port => 9000 => 9000
yasd.depth => 1 => 1
yasd.log_level => -1 => -1
yasd.max_executed_opline_num => 0 => 0
xdebug.coverage_enable => 1 => 1
xdebug.profiler_enable => 1 => 1
xdebug.remote_autostart => 1 => 1
xdebug.remote_connect_back => 0 => 0
xdebug.remote_mode => req => req
还会出现下面两种问题
corrupted size vs. prev_size
free(): invalid next size (fast)
[valgrind.log](https://github.com/swoole/yasd/files/5924247/valgrind.log)

**Comment by huanghantao** [comment]
方便加一个微信吗？我的微信：`codinghuang`

**Comment by ZhangTianyi-1998** [comment]
加您了

**Comment by huanghantao** [comment]
初步判断是因为某种原因，导致堆栈被破坏了
