### ISSUE TITLE
Why it says that is supports phpstorm ide, when tests cases for phpstorm compatability fail

### ISSUE THREAD

**Issue by juslintek** [swoole/yasd#95]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provides a simple script and debug step to reproduce the problem.

make test

2. What did you expect to see?

All passed

3. What did you see instead?

```c
Don't forget to run 'make test'.


=====================================================================
PHP         : /usr/local/Cellar/php/8.0.2/bin/php
PHP_SAPI    : cli
PHP_VERSION : 8.0.2
ZEND_VERSION: 4.0.2
PHP_OS      : Darwin - Darwin Linass-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
INI actual  : /Users/juslintek/yasd/tmp-php.ini
More .INIs  :
---------------------------------------------------------------------
PHP         : /usr/local/Cellar/php/8.0.2/bin/phpdbg
PHP_SAPI    : phpdbg
PHP_VERSION : 8.0.2
ZEND_VERSION: 4.0.2
PHP_OS      : Darwin - Darwin Linass-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
INI actual  : /Users/juslintek/yasd/tmp-php.ini
More .INIs  :
---------------------------------------------------------------------
CWD         : /Users/juslintek/yasd
Extra dirs  :
VALGRIND    : Not used
=====================================================================
TIME START 2021-02-22 09:43:21
=====================================================================
FAIL issue: 41 [tests/yasd_debugger/issue/41.phpt]
PASS opcode: getOpcodeByName [tests/yasd_debugger/opcode/getOpcodeByName.phpt]
FAIL remote_mode: breakpoint_list [tests/yasd_debugger/remote_mode/breakpoint_list.phpt]
FAIL remote_mode: breakpoint_set [tests/yasd_debugger/remote_mode/breakpoint_set/breakpoint_set.phpt]
TEST 5/20 [tests/yasd_debugger/remote_mode/breakpoint_set/breakpoint_set_conditiFAIL breakpoint_set: breakpoint_set_conditional_line [tests/yasd_debugger/remote_mode/breakpoint_set/breakpoint_set_conditional_line.phpt]
FAIL remote_mode: context_get [tests/yasd_debugger/remote_mode/context_get.phpt]
TEST 7/20 [tests/yasd_debugger/remote_mode/context_get/superglobal_variable.phptFAIL context_get: superglobal_variable [tests/yasd_debugger/remote_mode/context_get/superglobal_variable.phpt]
FAIL remote_mode: context_names [tests/yasd_debugger/remote_mode/context_names.phpt]
FAIL remote_mode: eval [tests/yasd_debugger/remote_mode/eval.phpt]
FAIL remote_mode: feature_set [tests/yasd_debugger/remote_mode/feature_set.phpt]
TEST 11/20 [tests/yasd_debugger/remote_mode/infinite_loop_detection/for_loop.phpFAIL infinite_loop_detection: for_loop [tests/yasd_debugger/remote_mode/infinite_loop_detection/for_loop.phpt]
TEST 12/20 [tests/yasd_debugger/remote_mode/infinite_loop_detection/goto_label_lFAIL infinite_loop_detection: goto_label_loop [tests/yasd_debugger/remote_mode/infinite_loop_detection/goto_label_loop.phpt]
TEST 13/20 [tests/yasd_debugger/remote_mode/phpstorm/compatible_with_phpstorm.phFAIL phpstorm: compatible_with_phpstorm [tests/yasd_debugger/remote_mode/phpstorm/compatible_with_phpstorm.phpt]
FAIL phpstorm: eval [tests/yasd_debugger/remote_mode/phpstorm/eval.phpt]
TEST 15/20 [tests/yasd_debugger/remote_mode/property_get/classnamme_array_key.phFAIL property_get: classnamme_array_key [tests/yasd_debugger/remote_mode/property_get/classnamme_array_key.phpt]
TEST 16/20 [tests/yasd_debugger/remote_mode/property_get/nmerical_index_array.phFAIL property_get: nmerical_index_array [tests/yasd_debugger/remote_mode/property_get/nmerical_index_array.phpt]
FAIL remote_mode: stack_get [tests/yasd_debugger/remote_mode/stack_get.phpt]
FAIL remote_mode: stdout [tests/yasd_debugger/remote_mode/stdout.phpt]
FAIL remote_mode: stop [tests/yasd_debugger/remote_mode/stop.phpt]
PASS zval: getRefCount [tests/yasd_debugger/zval/getRefCount.phpt]
=====================================================================
TIME END 2021-02-22 09:43:22

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   64
---------------------------------------------------------------------

Number of tests :   20                20
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :   18 ( 90.0%) ( 90.0%)
Tests passed    :    2 ( 10.0%) ( 10.0%)
---------------------------------------------------------------------
Time taken      :    1 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
issue: 41 [tests/yasd_debugger/issue/41.phpt]
remote_mode: breakpoint_list [tests/yasd_debugger/remote_mode/breakpoint_list.phpt]
remote_mode: breakpoint_set [tests/yasd_debugger/remote_mode/breakpoint_set/breakpoint_set.phpt]
breakpoint_set: breakpoint_set_conditional_line [tests/yasd_debugger/remote_mode/breakpoint_set/breakpoint_set_conditional_line.phpt]
remote_mode: context_get [tests/yasd_debugger/remote_mode/context_get.phpt]
context_get: superglobal_variable [tests/yasd_debugger/remote_mode/context_get/superglobal_variable.phpt]
remote_mode: context_names [tests/yasd_debugger/remote_mode/context_names.phpt]
remote_mode: eval [tests/yasd_debugger/remote_mode/eval.phpt]
remote_mode: feature_set [tests/yasd_debugger/remote_mode/feature_set.phpt]
infinite_loop_detection: for_loop [tests/yasd_debugger/remote_mode/infinite_loop_detection/for_loop.phpt]
infinite_loop_detection: goto_label_loop [tests/yasd_debugger/remote_mode/infinite_loop_detection/goto_label_loop.phpt]
phpstorm: compatible_with_phpstorm [tests/yasd_debugger/remote_mode/phpstorm/compatible_with_phpstorm.phpt]
phpstorm: eval [tests/yasd_debugger/remote_mode/phpstorm/eval.phpt]
property_get: classnamme_array_key [tests/yasd_debugger/remote_mode/property_get/classnamme_array_key.phpt]
property_get: nmerical_index_array [tests/yasd_debugger/remote_mode/property_get/nmerical_index_array.phpt]
remote_mode: stack_get [tests/yasd_debugger/remote_mode/stack_get.phpt]
remote_mode: stdout [tests/yasd_debugger/remote_mode/stdout.phpt]
remote_mode: stop [tests/yasd_debugger/remote_mode/stop.phpt]
=====================================================================

You may have found a problem in PHP.
This report can be automatically sent to the PHP QA team at
http://qa.php.net/reports and http://news.php.net/php.qa.reports
This gives us a better understanding of PHP's behavior.
If you don't want to send the report immediately you can choose
option "s" to save it.	You can then email it to qa-reports@lists.php.net later.
Do you want to send this report now? [Yns]: Y

Please enter your email address.
(Your address will be mangled so that it will not go out on any
mailinglist in plain text): jusys.linas@gmail.com

Posting to http://qa.php.net/buildtest-process.php

Thank you for helping to make PHP better.
make: *** [test] Error 1
```

4. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
uname -a
```
Darwin Linass-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```
php -v
```
PHP 8.0.2 (cli) (built: Feb  4 2021 18:57:55) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies
```
gcc - v
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by juslintek** [comment]
And as expected it doesn't work with phpstorm ide so it renders it kind of usless. That command line debugging too time consuming.

**Comment by huanghantao** [comment]
Your test environment is not initialized well, you can look at YASD's CI:

https://github.com/swoole/yasd/actions

**Comment by hq9000** [comment]
so is it expected to work with phpstorm or not?

I'm also unable to get it stop on breakpoints.

**Comment by juslintek** [comment]
Even if tests pass probably they do not cover actual PHPStorm behaviour. Because I cannot make a breakpoint with this extension as well. I enable that yasd would send debug requests on evey request from docker php:alpine. But it seems phpstorm ignore everything send from yasd or yasd is not sending, haven't configured logs for it to see if there is connectivity issue. But with same image, but xdebug 3 installed with xdebug.mode=debug works without any problems, unless I enable swoole extension. :D

**Comment by hq9000** [comment]
Btw, it's said it supports vscode. Any luck with that one?

**Comment by huanghantao** [comment]
Yasd supports vscode and phpstorm. Maybe you should show me how you configure yasd?

**Comment by hq9000** [comment]
okay.

## The php-side setup
1. I'm running my php app in docker, the complete Dockerfile: https://gist.github.com/hq9000/f2fbb8dcf6a2a3799615064f2f9c5b5e
2. I run the container with "host" networking and volume mapping that preserves path to my php files: `/home/me -> /home/me`
3. the configuration reported by php is as follows: 
```
root@sergey-Aspire-A315-53G:/# php --ri yasd  

yasd

Yasd => enabled
Author => codinghuang <codinghuang@qq.com>
Version => 0.3.7
Built => Mar  2 2021 15:56:17

Directive => Local Value => Master Value
yasd.breakpoints_file => no value => no value
yasd.debug_mode => remote => remote
yasd.remote_host => 127.0.0.1 => 127.0.0.1
yasd.remote_port => 9337 => 9337
yasd.depth => 1 => 1
yasd.log_level => -1 => -1
yasd.max_executed_opline_num => 0 => 0
yasd.init_file => no value => no value
xdebug.coverage_enable => 1 => 1
xdebug.profiler_enable => 1 => 1
xdebug.remote_autostart => 1 => 1
xdebug.remote_connect_back => 0 => 0
xdebug.remote_mode => req => req

root@sergey-Aspire-A315-53G:/# php -a
Interactive shell

php > print swoole_version();
4.6.3
```

## Phpstorm-side setup

phpstorm version: **2020.1** (bit old)

configuration of the "interpreter":
![image](https://user-images.githubusercontent.com/21345604/109755043-471a2880-7bf6-11eb-8b89-992f07b7e884.png)


I have a simple script where i have set breakpoints at each and every line:
![image](https://user-images.githubusercontent.com/21345604/109754815-c78c5980-7bf5-11eb-9ad8-d500478c7993.png)

run configuration:
![image](https://user-images.githubusercontent.com/21345604/109754940-08846e00-7bf6-11eb-9e08-70f015e79992.png)

debug settings:
![image](https://user-images.githubusercontent.com/21345604/109755115-66b15100-7bf6-11eb-8671-a12e1435bd61.png)

## Expectation

in the setup above, I was expecting to have the first breakpoint hit when clicking here:
![image](https://user-images.githubusercontent.com/21345604/109755184-91030e80-7bf6-11eb-982a-4df68fcefa79.png)

however, it does not happen

if i click on the "bug" icon instead, it gets me this:
![image](https://user-images.githubusercontent.com/21345604/109755642-6796b280-7bf7-11eb-89b2-6e4238f2ac69.png)

running a container from that image, i can confirm that it can reach the phpstorm's port:
![image](https://user-images.githubusercontent.com/21345604/109755999-1cc96a80-7bf8-11eb-814e-016b4ef6ee54.png)

**Comment by hq9000** [comment]
also i tried to enable some log by setting yasd.log_level = 3, the setting was applied:
![image](https://user-images.githubusercontent.com/21345604/109757475-e6411f00-7bfa-11eb-942b-60604034ee11.png)

but i dont' see any yasd-related logs appearing. Maybe i just don't know where to look for them.

**Comment by huanghantao** [comment]
First, click the "Listen" button instead of "Run" button.
<img width="340" alt="image" src="https://user-images.githubusercontent.com/22836925/109843748-5fd21f00-7c86-11eb-8b5f-03ce10fb8428.png">

Second, execute your script with `-e` option, for example:

```bash
php -e test.php
```

**Comment by hq9000** [comment]
yes, the thing was that i forgot to use "-e"
now it works thank you.

this pic i'll put into a readme update i will PR shortly

**Comment by huanghantao** [comment]
@hq9000 Thank you!

**Comment by juslintek** [comment]
Okay on my side setup is like that:
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/5687423/109955661-69da3900-7ceb-11eb-82d9-19212599b124.png">
<img width="1774" alt="image" src="https://user-images.githubusercontent.com/5687423/109956838-cc800480-7cec-11eb-835d-70708228b6b1.png">
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/5687423/109956944-ee798700-7cec-11eb-8e8e-c48a8db29806.png">

But when I enable swoole and yasd with above configurations, and run instead of `php artisan server` is docker `laravels` server. It does not work. I use same port as xdebug.

**Comment by hq9000** [comment]
@juslintek i use php 7.4. 
and, as i run in in CLI, so can't really comment about cookies and stuff.

**Comment by huanghantao** [comment]
@juslintek Yasd is not xdebug or sdebug, so you cannot use yasd in the same way as xdebug. The use of yasd is very easy, just click the listen button of phpstorm, and then execute php with -e. Don't need to configure cookies etc.

Do you use a virtual machine or container, and, you need to show me how you configure yasd:

```bash
php --ri yasd
```

**Comment by huanghantao** [comment]
Can you debug the test.php file in the yasd directory?

**Comment by juslintek** [comment]
@huanghantao yes.

**Comment by juslintek** [comment]
Okay actually I lied, I haven't tried, when I tried with file like this:
```
<?php

echo "test";

$something = "black";

if ($something === "black") {
    echo true;
}
```
I even checked break at first line. And nothing helped. I've ran from inside alpine php docker container on which I've compiled yasd with swoole.

so I run:
```
php -e test.php
```
and IDE is not opening debug inspection view...

**Comment by juslintek** [comment]
Guess I'll just go back to sdebug and wait for it to support php8, then upgrade to it. :-(

**Comment by juslintek** [comment]
So final result of YASD is that it is not working with PHPStorm 2020.3.2 and latest Early Access, while using Docker.

**Comment by gotys** [comment]
I confirm that YASD works with PhpStorm 2020.3 , with breakpoints and everything.
If you want your breakpoints to work , you have to set your IDE for remote file mappings
![xdebug](https://user-images.githubusercontent.com/272523/111417005-4947b100-86e5-11eb-9b8c-ccdbbb69b0d2.png)

**Comment by superdav42** [comment]
Anyone get PhpStorm and YASD to work without using docker? I just compiled yasd 0.3.7 manually and would expect it to work without needing to map any paths. It's connecting to PhpStorm just not stopping and any of the breakpoints set. Same results using master branch.

```
 php --ri yasd

yasd

Yasd => enabled
Author => codinghuang <codinghuang@qq.com>
Version => 0.3.7
Built => Mar 23 2021 13:16:05

Directive => Local Value => Master Value
yasd.breakpoints_file => no value => no value
yasd.debug_mode => remote => remote
yasd.remote_host => 127.0.0.1 => 127.0.0.1
yasd.remote_port => 9000 => 9000
yasd.depth => 1 => 1
yasd.log_level => 3 => 3
yasd.max_executed_opline_num => 0 => 0
xdebug.coverage_enable => 1 => 1
xdebug.profiler_enable => 1 => 1
xdebug.remote_autostart => 1 => 1
xdebug.remote_connect_back => 0 => 0
xdebug.remote_mode => req => req
```
NetBeans debug config just like shown above and release 2020.3.3.
I am invoking with `-e` like `php -e test.php`

What could the problem be? Is there any more resources like debug logs I can use to troubleshoot this? It seems PhpStorm is not passing the breakpoints correctly to yasd but I don't know where to begin to correct it.

**Comment by juslintek** [comment]
> Anyone get PhpStorm and YASD to work without using docker? I just compiled yasd 0.3.7 manually and would expect it to work without needing to map any paths. It's connecting to PhpStorm just not stopping and any of the breakpoints set. Same results using master branch.
> 
> ```
>  php --ri yasd
> 
> yasd
> 
> Yasd => enabled
> Author => codinghuang <codinghuang@qq.com>
> Version => 0.3.7
> Built => Mar 23 2021 13:16:05
> 
> Directive => Local Value => Master Value
> yasd.breakpoints_file => no value => no value
> yasd.debug_mode => remote => remote
> yasd.remote_host => 127.0.0.1 => 127.0.0.1
> yasd.remote_port => 9000 => 9000
> yasd.depth => 1 => 1
> yasd.log_level => 3 => 3
> yasd.max_executed_opline_num => 0 => 0
> xdebug.coverage_enable => 1 => 1
> xdebug.profiler_enable => 1 => 1
> xdebug.remote_autostart => 1 => 1
> xdebug.remote_connect_back => 0 => 0
> xdebug.remote_mode => req => req
> ```
> 
> NetBeans debug config just like shown above and release 2020.3.3.
> I am invoking with `-e` like `php -e test.php`
> 
> What could the problem be? Is there any more resources like debug logs I can use to troubleshoot this? It seems PhpStorm is not passing the breakpoints correctly to yasd but I don't know where to begin to correct it.

Seems like its not working for me. If I run `php -e` while yasd is enabled I get this problem: https://github.com/swoole/yasd/issues/99

If I run without `-e` still it is not working, probably because it must know IP address to send debug data to, but it cannot resolve my IP still inside of docker.

**Comment by huanghantao** [comment]
@superdav42 You can configure the following configuration:

```ini
yasd.log_level=0
```

You will get a file called debug.log in your current directory.

**Comment by huanghantao** [comment]
@superdav42 It is recommended that you first debug the `test.php` file under the yasd directory, and then debug your own project after success.

**Comment by janskopljak** [comment]
@gotys What is your server setup? I have `[yasd] connection refused` issues popping up when I try to run `php -e test.php` inside my docker container

**Comment by domgraziano** [comment]
> @gotys What is your server setup? I have `[yasd] connection refused` issues popping up when I try to run `php -e test.php` inside my docker container
> 
same here

**Comment by deminy** [comment]
How to debug a Swoole-based web server using _yasd_ (Yet Another Swoole Debugger) in Phpstorm?

Please check here: [https://github.com/swoole/docker-swoole/tree/master/examples/35-debug-with-yasd](https://github.com/swoole/docker-swoole/tree/master/examples/35-debug-with-yasd)
