### ISSUE TITLE
php -e causes Invalid address/ Address not supported: No error information, when yasd is enabled

### ISSUE THREAD

**Issue by juslintek** [swoole/yasd#99]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provides a simple script and debug step to reproduce the problem.
I run 

```
php -e test.php
```
test file: test.php
```php
<?php echo "test";
```

2. What did you expect to see?
I expected to see no problems and it to work without problems.

3. What did you see instead?
> Invalid address/ Address not supported: No error information

4. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
~ # uname -a
Linux 3ea8ae99125a 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 Linux


~ # php -v
PHP 7.4.15 (cli) (built: Feb 18 2021 00:45:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Yasd v0.3.7, Our Copyright, by codinghuang

~ # gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/10.2.1/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-10.2.1_pre1/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 10.2.1_pre1' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-cloog-backend --enable-languages=c,c++,d,objc,go,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.1 20201203 (Alpine 10.2.1_pre1) 


Figured it out... Seems that yasd does not support hostnames, only ips...

**Comment by huanghantao** [comment]
@juslintek You can use the latest yasd code of the master branch, and then use the init_file file #98 #97

**Comment by juslintek** [comment]
I personally prefer to exclude debugging deps from code unless they inject from packages and latch onto hooks of framework. I do it like this on entrypoint.sh:
```
DEBUG_LISTENER_IP=$(ping -c 1 $DOCKER_HOSTNAME | grep "): " | sed -E 's/.*\((.*)\).*/\1/g')

sed -i "s/yasd.remote_host=.*/yasd.remote_host=${DEBUG_LISTENER_IP}/" /usr/local/etc/php/conf.d/20-yasd.ini
```

But I actually still have a problem of phpstorm ide not stopping on breakpoint...

**Comment by huanghantao** [comment]
Have you configured path mapping?

**Comment by juslintek** [comment]
@huanghantao yes path mapping is configured. :-)

**Comment by janskopljak** [comment]
Any news on this one?

**Comment by juslintek** [comment]
@huanghantao hasn't resolved it, configuration of yasd.remote_host is not accepting fqdn or hostname it must be IP.
So @janskopljak make sure you use IP or do As I did, resolve hostname to IP. But still for me it seems like there are other issues on top from yasd and docker side, because it cannot reach phpstorm.

**Comment by janskopljak** [comment]
@juslintek I acutally tried with the static ips, but I just get `[yasd] connection refused` issues no matter what I try

**Comment by juslintek** [comment]
@janskopljak have you used `-e` flag on PHP. Basically, I can debug single file executions, but cannot debug swoole server. :-)

I run PHPUnit or any command-line tools with PHP -e flag and have these settings set and it works:
![image](https://user-images.githubusercontent.com/5687423/118189271-3b46b000-b44a-11eb-8c64-a143b26a0573.png)

Do not run in it debug mode, just make sure "Start Listening for PHP Debug Connections" is enabled
![image](https://user-images.githubusercontent.com/5687423/118189352-56192480-b44a-11eb-9e13-1268b4f83a96.png)

Yasd is a very bad debugger :-) When you try to evaluate it with some value it allows you to do that only for a single run. After that, it returns null all the time. Or when you try to open larger data sets it crashes.

And because of that, I will quit swoole. It is too much hassle to debug, if you have a complex application it really big overhead to not be able to debug your code properly.
